package com.trj.jk.web.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoanAuditCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    public LoanAuditCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdIsNull() {
            addCriterion("apply_loan_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdIsNotNull() {
            addCriterion("apply_loan_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdEqualTo(Integer value) {
            addCriterion("apply_loan_id =", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdNotEqualTo(Integer value) {
            addCriterion("apply_loan_id <>", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdGreaterThan(Integer value) {
            addCriterion("apply_loan_id >", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_loan_id >=", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdLessThan(Integer value) {
            addCriterion("apply_loan_id <", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdLessThanOrEqualTo(Integer value) {
            addCriterion("apply_loan_id <=", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdIn(List<Integer> values) {
            addCriterion("apply_loan_id in", values, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdNotIn(List<Integer> values) {
            addCriterion("apply_loan_id not in", values, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdBetween(Integer value1, Integer value2) {
            addCriterion("apply_loan_id between", value1, value2, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_loan_id not between", value1, value2, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andTotalChargeIsNull() {
            addCriterion("total_charge is null");
            return (Criteria) this;
        }

        public Criteria andTotalChargeIsNotNull() {
            addCriterion("total_charge is not null");
            return (Criteria) this;
        }

        public Criteria andTotalChargeEqualTo(BigDecimal value) {
            addCriterion("total_charge =", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeNotEqualTo(BigDecimal value) {
            addCriterion("total_charge <>", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeGreaterThan(BigDecimal value) {
            addCriterion("total_charge >", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_charge >=", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeLessThan(BigDecimal value) {
            addCriterion("total_charge <", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_charge <=", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeIn(List<BigDecimal> values) {
            addCriterion("total_charge in", values, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeNotIn(List<BigDecimal> values) {
            addCriterion("total_charge not in", values, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_charge between", value1, value2, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_charge not between", value1, value2, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andCutChargeIsNull() {
            addCriterion("cut_charge is null");
            return (Criteria) this;
        }

        public Criteria andCutChargeIsNotNull() {
            addCriterion("cut_charge is not null");
            return (Criteria) this;
        }

        public Criteria andCutChargeEqualTo(BigDecimal value) {
            addCriterion("cut_charge =", value, "cutCharge");
            return (Criteria) this;
        }

        public Criteria andCutChargeNotEqualTo(BigDecimal value) {
            addCriterion("cut_charge <>", value, "cutCharge");
            return (Criteria) this;
        }

        public Criteria andCutChargeGreaterThan(BigDecimal value) {
            addCriterion("cut_charge >", value, "cutCharge");
            return (Criteria) this;
        }

        public Criteria andCutChargeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cut_charge >=", value, "cutCharge");
            return (Criteria) this;
        }

        public Criteria andCutChargeLessThan(BigDecimal value) {
            addCriterion("cut_charge <", value, "cutCharge");
            return (Criteria) this;
        }

        public Criteria andCutChargeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cut_charge <=", value, "cutCharge");
            return (Criteria) this;
        }

        public Criteria andCutChargeIn(List<BigDecimal> values) {
            addCriterion("cut_charge in", values, "cutCharge");
            return (Criteria) this;
        }

        public Criteria andCutChargeNotIn(List<BigDecimal> values) {
            addCriterion("cut_charge not in", values, "cutCharge");
            return (Criteria) this;
        }

        public Criteria andCutChargeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cut_charge between", value1, value2, "cutCharge");
            return (Criteria) this;
        }

        public Criteria andCutChargeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cut_charge not between", value1, value2, "cutCharge");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("audit_time is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("audit_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Date value) {
            addCriterion("audit_time =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Date value) {
            addCriterion("audit_time <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Date value) {
            addCriterion("audit_time >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("audit_time >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Date value) {
            addCriterion("audit_time <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("audit_time <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Date> values) {
            addCriterion("audit_time in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Date> values) {
            addCriterion("audit_time not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Date value1, Date value2) {
            addCriterion("audit_time between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("audit_time not between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andRepayTypeIsNull() {
            addCriterion("repay_type is null");
            return (Criteria) this;
        }

        public Criteria andRepayTypeIsNotNull() {
            addCriterion("repay_type is not null");
            return (Criteria) this;
        }

        public Criteria andRepayTypeEqualTo(String value) {
            addCriterion("repay_type =", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeNotEqualTo(String value) {
            addCriterion("repay_type <>", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeGreaterThan(String value) {
            addCriterion("repay_type >", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeGreaterThanOrEqualTo(String value) {
            addCriterion("repay_type >=", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeLessThan(String value) {
            addCriterion("repay_type <", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeLessThanOrEqualTo(String value) {
            addCriterion("repay_type <=", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeLike(String value) {
            addCriterion("repay_type like", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeNotLike(String value) {
            addCriterion("repay_type not like", value, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeIn(List<String> values) {
            addCriterion("repay_type in", values, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeNotIn(List<String> values) {
            addCriterion("repay_type not in", values, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeBetween(String value1, String value2) {
            addCriterion("repay_type between", value1, value2, "repayType");
            return (Criteria) this;
        }

        public Criteria andRepayTypeNotBetween(String value1, String value2) {
            addCriterion("repay_type not between", value1, value2, "repayType");
            return (Criteria) this;
        }

        public Criteria andAmountLimitIsNull() {
            addCriterion("amount_limit is null");
            return (Criteria) this;
        }

        public Criteria andAmountLimitIsNotNull() {
            addCriterion("amount_limit is not null");
            return (Criteria) this;
        }

        public Criteria andAmountLimitEqualTo(BigDecimal value) {
            addCriterion("amount_limit =", value, "amountLimit");
            return (Criteria) this;
        }

        public Criteria andAmountLimitNotEqualTo(BigDecimal value) {
            addCriterion("amount_limit <>", value, "amountLimit");
            return (Criteria) this;
        }

        public Criteria andAmountLimitGreaterThan(BigDecimal value) {
            addCriterion("amount_limit >", value, "amountLimit");
            return (Criteria) this;
        }

        public Criteria andAmountLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount_limit >=", value, "amountLimit");
            return (Criteria) this;
        }

        public Criteria andAmountLimitLessThan(BigDecimal value) {
            addCriterion("amount_limit <", value, "amountLimit");
            return (Criteria) this;
        }

        public Criteria andAmountLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount_limit <=", value, "amountLimit");
            return (Criteria) this;
        }

        public Criteria andAmountLimitIn(List<BigDecimal> values) {
            addCriterion("amount_limit in", values, "amountLimit");
            return (Criteria) this;
        }

        public Criteria andAmountLimitNotIn(List<BigDecimal> values) {
            addCriterion("amount_limit not in", values, "amountLimit");
            return (Criteria) this;
        }

        public Criteria andAmountLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount_limit between", value1, value2, "amountLimit");
            return (Criteria) this;
        }

        public Criteria andAmountLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount_limit not between", value1, value2, "amountLimit");
            return (Criteria) this;
        }

        public Criteria andRestLimitIsNull() {
            addCriterion("rest_limit is null");
            return (Criteria) this;
        }

        public Criteria andRestLimitIsNotNull() {
            addCriterion("rest_limit is not null");
            return (Criteria) this;
        }

        public Criteria andRestLimitEqualTo(BigDecimal value) {
            addCriterion("rest_limit =", value, "restLimit");
            return (Criteria) this;
        }

        public Criteria andRestLimitNotEqualTo(BigDecimal value) {
            addCriterion("rest_limit <>", value, "restLimit");
            return (Criteria) this;
        }

        public Criteria andRestLimitGreaterThan(BigDecimal value) {
            addCriterion("rest_limit >", value, "restLimit");
            return (Criteria) this;
        }

        public Criteria andRestLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rest_limit >=", value, "restLimit");
            return (Criteria) this;
        }

        public Criteria andRestLimitLessThan(BigDecimal value) {
            addCriterion("rest_limit <", value, "restLimit");
            return (Criteria) this;
        }

        public Criteria andRestLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rest_limit <=", value, "restLimit");
            return (Criteria) this;
        }

        public Criteria andRestLimitIn(List<BigDecimal> values) {
            addCriterion("rest_limit in", values, "restLimit");
            return (Criteria) this;
        }

        public Criteria andRestLimitNotIn(List<BigDecimal> values) {
            addCriterion("rest_limit not in", values, "restLimit");
            return (Criteria) this;
        }

        public Criteria andRestLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rest_limit between", value1, value2, "restLimit");
            return (Criteria) this;
        }

        public Criteria andRestLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rest_limit not between", value1, value2, "restLimit");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1IsNull() {
            addCriterion("amount_limit_calculate_1 is null");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1IsNotNull() {
            addCriterion("amount_limit_calculate_1 is not null");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1EqualTo(BigDecimal value) {
            addCriterion("amount_limit_calculate_1 =", value, "amountLimitCalculate1");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1NotEqualTo(BigDecimal value) {
            addCriterion("amount_limit_calculate_1 <>", value, "amountLimitCalculate1");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1GreaterThan(BigDecimal value) {
            addCriterion("amount_limit_calculate_1 >", value, "amountLimitCalculate1");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount_limit_calculate_1 >=", value, "amountLimitCalculate1");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1LessThan(BigDecimal value) {
            addCriterion("amount_limit_calculate_1 <", value, "amountLimitCalculate1");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount_limit_calculate_1 <=", value, "amountLimitCalculate1");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1In(List<BigDecimal> values) {
            addCriterion("amount_limit_calculate_1 in", values, "amountLimitCalculate1");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1NotIn(List<BigDecimal> values) {
            addCriterion("amount_limit_calculate_1 not in", values, "amountLimitCalculate1");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount_limit_calculate_1 between", value1, value2, "amountLimitCalculate1");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount_limit_calculate_1 not between", value1, value2, "amountLimitCalculate1");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2IsNull() {
            addCriterion("amount_limit_calculate_2 is null");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2IsNotNull() {
            addCriterion("amount_limit_calculate_2 is not null");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2EqualTo(BigDecimal value) {
            addCriterion("amount_limit_calculate_2 =", value, "amountLimitCalculate2");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2NotEqualTo(BigDecimal value) {
            addCriterion("amount_limit_calculate_2 <>", value, "amountLimitCalculate2");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2GreaterThan(BigDecimal value) {
            addCriterion("amount_limit_calculate_2 >", value, "amountLimitCalculate2");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount_limit_calculate_2 >=", value, "amountLimitCalculate2");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2LessThan(BigDecimal value) {
            addCriterion("amount_limit_calculate_2 <", value, "amountLimitCalculate2");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount_limit_calculate_2 <=", value, "amountLimitCalculate2");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2In(List<BigDecimal> values) {
            addCriterion("amount_limit_calculate_2 in", values, "amountLimitCalculate2");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2NotIn(List<BigDecimal> values) {
            addCriterion("amount_limit_calculate_2 not in", values, "amountLimitCalculate2");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount_limit_calculate_2 between", value1, value2, "amountLimitCalculate2");
            return (Criteria) this;
        }

        public Criteria andAmountLimitCalculate2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount_limit_calculate_2 not between", value1, value2, "amountLimitCalculate2");
            return (Criteria) this;
        }

        public Criteria andTerm1IsNull() {
            addCriterion("term_1 is null");
            return (Criteria) this;
        }

        public Criteria andTerm1IsNotNull() {
            addCriterion("term_1 is not null");
            return (Criteria) this;
        }

        public Criteria andTerm1EqualTo(String value) {
            addCriterion("term_1 =", value, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm1NotEqualTo(String value) {
            addCriterion("term_1 <>", value, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm1GreaterThan(String value) {
            addCriterion("term_1 >", value, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm1GreaterThanOrEqualTo(String value) {
            addCriterion("term_1 >=", value, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm1LessThan(String value) {
            addCriterion("term_1 <", value, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm1LessThanOrEqualTo(String value) {
            addCriterion("term_1 <=", value, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm1Like(String value) {
            addCriterion("term_1 like", value, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm1NotLike(String value) {
            addCriterion("term_1 not like", value, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm1In(List<String> values) {
            addCriterion("term_1 in", values, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm1NotIn(List<String> values) {
            addCriterion("term_1 not in", values, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm1Between(String value1, String value2) {
            addCriterion("term_1 between", value1, value2, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm1NotBetween(String value1, String value2) {
            addCriterion("term_1 not between", value1, value2, "term1");
            return (Criteria) this;
        }

        public Criteria andTerm2IsNull() {
            addCriterion("term_2 is null");
            return (Criteria) this;
        }

        public Criteria andTerm2IsNotNull() {
            addCriterion("term_2 is not null");
            return (Criteria) this;
        }

        public Criteria andTerm2EqualTo(String value) {
            addCriterion("term_2 =", value, "term2");
            return (Criteria) this;
        }

        public Criteria andTerm2NotEqualTo(String value) {
            addCriterion("term_2 <>", value, "term2");
            return (Criteria) this;
        }

        public Criteria andTerm2GreaterThan(String value) {
            addCriterion("term_2 >", value, "term2");
            return (Criteria) this;
        }

        public Criteria andTerm2GreaterThanOrEqualTo(String value) {
            addCriterion("term_2 >=", value, "term2");
            return (Criteria) this;
        }

        public Criteria andTerm2LessThan(String value) {
            addCriterion("term_2 <", value, "term2");
            return (Criteria) this;
        }

        public Criteria andTerm2LessThanOrEqualTo(String value) {
            addCriterion("term_2 <=", value, "term2");
            return (Criteria) this;
        }

        public Criteria andTerm2Like(String value) {
            addCriterion("term_2 like", value, "term2");
            return (Criteria) this;
        }

        public Criteria andTerm2NotLike(String value) {
            addCriterion("term_2 not like", value, "term2");
            return (Criteria) this;
        }

        public Criteria andTerm2In(List<String> values) {
            addCriterion("term_2 in", values, "term2");
            return (Criteria) this;
        }

        public Criteria andTerm2NotIn(List<String> values) {
            addCriterion("term_2 not in", values, "term2");
            return (Criteria) this;
        }

        public Criteria andTerm2Between(String value1, String value2) {
            addCriterion("term_2 between", value1, value2, "term2");
            return (Criteria) this;
        }

        public Criteria andTerm2NotBetween(String value1, String value2) {
            addCriterion("term_2 not between", value1, value2, "term2");
            return (Criteria) this;
        }

        public Criteria andInterestIsNull() {
            addCriterion("interest is null");
            return (Criteria) this;
        }

        public Criteria andInterestIsNotNull() {
            addCriterion("interest is not null");
            return (Criteria) this;
        }

        public Criteria andInterestEqualTo(BigDecimal value) {
            addCriterion("interest =", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotEqualTo(BigDecimal value) {
            addCriterion("interest <>", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThan(BigDecimal value) {
            addCriterion("interest >", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("interest >=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThan(BigDecimal value) {
            addCriterion("interest <", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThanOrEqualTo(BigDecimal value) {
            addCriterion("interest <=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestIn(List<BigDecimal> values) {
            addCriterion("interest in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotIn(List<BigDecimal> values) {
            addCriterion("interest not in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest not between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andOpinionIsNull() {
            addCriterion("opinion is null");
            return (Criteria) this;
        }

        public Criteria andOpinionIsNotNull() {
            addCriterion("opinion is not null");
            return (Criteria) this;
        }

        public Criteria andOpinionEqualTo(String value) {
            addCriterion("opinion =", value, "opinion");
            return (Criteria) this;
        }

        public Criteria andOpinionNotEqualTo(String value) {
            addCriterion("opinion <>", value, "opinion");
            return (Criteria) this;
        }

        public Criteria andOpinionGreaterThan(String value) {
            addCriterion("opinion >", value, "opinion");
            return (Criteria) this;
        }

        public Criteria andOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("opinion >=", value, "opinion");
            return (Criteria) this;
        }

        public Criteria andOpinionLessThan(String value) {
            addCriterion("opinion <", value, "opinion");
            return (Criteria) this;
        }

        public Criteria andOpinionLessThanOrEqualTo(String value) {
            addCriterion("opinion <=", value, "opinion");
            return (Criteria) this;
        }

        public Criteria andOpinionLike(String value) {
            addCriterion("opinion like", value, "opinion");
            return (Criteria) this;
        }

        public Criteria andOpinionNotLike(String value) {
            addCriterion("opinion not like", value, "opinion");
            return (Criteria) this;
        }

        public Criteria andOpinionIn(List<String> values) {
            addCriterion("opinion in", values, "opinion");
            return (Criteria) this;
        }

        public Criteria andOpinionNotIn(List<String> values) {
            addCriterion("opinion not in", values, "opinion");
            return (Criteria) this;
        }

        public Criteria andOpinionBetween(String value1, String value2) {
            addCriterion("opinion between", value1, value2, "opinion");
            return (Criteria) this;
        }

        public Criteria andOpinionNotBetween(String value1, String value2) {
            addCriterion("opinion not between", value1, value2, "opinion");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRateTypeIsNull() {
            addCriterion("rate_type is null");
            return (Criteria) this;
        }

        public Criteria andRateTypeIsNotNull() {
            addCriterion("rate_type is not null");
            return (Criteria) this;
        }

        public Criteria andRateTypeEqualTo(Byte value) {
            addCriterion("rate_type =", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeNotEqualTo(Byte value) {
            addCriterion("rate_type <>", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeGreaterThan(Byte value) {
            addCriterion("rate_type >", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("rate_type >=", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeLessThan(Byte value) {
            addCriterion("rate_type <", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeLessThanOrEqualTo(Byte value) {
            addCriterion("rate_type <=", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeIn(List<Byte> values) {
            addCriterion("rate_type in", values, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeNotIn(List<Byte> values) {
            addCriterion("rate_type not in", values, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeBetween(Byte value1, Byte value2) {
            addCriterion("rate_type between", value1, value2, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("rate_type not between", value1, value2, "rateType");
            return (Criteria) this;
        }

        public Criteria andTermUnitIsNull() {
            addCriterion("term_unit is null");
            return (Criteria) this;
        }

        public Criteria andTermUnitIsNotNull() {
            addCriterion("term_unit is not null");
            return (Criteria) this;
        }

        public Criteria andTermUnitEqualTo(String value) {
            addCriterion("term_unit =", value, "termUnit");
            return (Criteria) this;
        }

        public Criteria andTermUnitNotEqualTo(String value) {
            addCriterion("term_unit <>", value, "termUnit");
            return (Criteria) this;
        }

        public Criteria andTermUnitGreaterThan(String value) {
            addCriterion("term_unit >", value, "termUnit");
            return (Criteria) this;
        }

        public Criteria andTermUnitGreaterThanOrEqualTo(String value) {
            addCriterion("term_unit >=", value, "termUnit");
            return (Criteria) this;
        }

        public Criteria andTermUnitLessThan(String value) {
            addCriterion("term_unit <", value, "termUnit");
            return (Criteria) this;
        }

        public Criteria andTermUnitLessThanOrEqualTo(String value) {
            addCriterion("term_unit <=", value, "termUnit");
            return (Criteria) this;
        }

        public Criteria andTermUnitLike(String value) {
            addCriterion("term_unit like", value, "termUnit");
            return (Criteria) this;
        }

        public Criteria andTermUnitNotLike(String value) {
            addCriterion("term_unit not like", value, "termUnit");
            return (Criteria) this;
        }

        public Criteria andTermUnitIn(List<String> values) {
            addCriterion("term_unit in", values, "termUnit");
            return (Criteria) this;
        }

        public Criteria andTermUnitNotIn(List<String> values) {
            addCriterion("term_unit not in", values, "termUnit");
            return (Criteria) this;
        }

        public Criteria andTermUnitBetween(String value1, String value2) {
            addCriterion("term_unit between", value1, value2, "termUnit");
            return (Criteria) this;
        }

        public Criteria andTermUnitNotBetween(String value1, String value2) {
            addCriterion("term_unit not between", value1, value2, "termUnit");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_audit
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 15 17:24:50 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_audit
     *
     * @mbg.generated Tue Aug 15 17:24:50 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}