package com.trj.jk.web.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoanApplyProfessionCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public LoanApplyProfessionCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdIsNull() {
            addCriterion("loan_apply_id is null");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdIsNotNull() {
            addCriterion("loan_apply_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdEqualTo(Integer value) {
            addCriterion("loan_apply_id =", value, "loanApplyId");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdNotEqualTo(Integer value) {
            addCriterion("loan_apply_id <>", value, "loanApplyId");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdGreaterThan(Integer value) {
            addCriterion("loan_apply_id >", value, "loanApplyId");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_apply_id >=", value, "loanApplyId");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdLessThan(Integer value) {
            addCriterion("loan_apply_id <", value, "loanApplyId");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdLessThanOrEqualTo(Integer value) {
            addCriterion("loan_apply_id <=", value, "loanApplyId");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdIn(List<Integer> values) {
            addCriterion("loan_apply_id in", values, "loanApplyId");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdNotIn(List<Integer> values) {
            addCriterion("loan_apply_id not in", values, "loanApplyId");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdBetween(Integer value1, Integer value2) {
            addCriterion("loan_apply_id between", value1, value2, "loanApplyId");
            return (Criteria) this;
        }

        public Criteria andLoanApplyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_apply_id not between", value1, value2, "loanApplyId");
            return (Criteria) this;
        }

        public Criteria andProfessionIdIsNull() {
            addCriterion("profession_id is null");
            return (Criteria) this;
        }

        public Criteria andProfessionIdIsNotNull() {
            addCriterion("profession_id is not null");
            return (Criteria) this;
        }

        public Criteria andProfessionIdEqualTo(Integer value) {
            addCriterion("profession_id =", value, "professionId");
            return (Criteria) this;
        }

        public Criteria andProfessionIdNotEqualTo(Integer value) {
            addCriterion("profession_id <>", value, "professionId");
            return (Criteria) this;
        }

        public Criteria andProfessionIdGreaterThan(Integer value) {
            addCriterion("profession_id >", value, "professionId");
            return (Criteria) this;
        }

        public Criteria andProfessionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("profession_id >=", value, "professionId");
            return (Criteria) this;
        }

        public Criteria andProfessionIdLessThan(Integer value) {
            addCriterion("profession_id <", value, "professionId");
            return (Criteria) this;
        }

        public Criteria andProfessionIdLessThanOrEqualTo(Integer value) {
            addCriterion("profession_id <=", value, "professionId");
            return (Criteria) this;
        }

        public Criteria andProfessionIdIn(List<Integer> values) {
            addCriterion("profession_id in", values, "professionId");
            return (Criteria) this;
        }

        public Criteria andProfessionIdNotIn(List<Integer> values) {
            addCriterion("profession_id not in", values, "professionId");
            return (Criteria) this;
        }

        public Criteria andProfessionIdBetween(Integer value1, Integer value2) {
            addCriterion("profession_id between", value1, value2, "professionId");
            return (Criteria) this;
        }

        public Criteria andProfessionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("profession_id not between", value1, value2, "professionId");
            return (Criteria) this;
        }

        public Criteria andCorpNameIsNull() {
            addCriterion("corp_name is null");
            return (Criteria) this;
        }

        public Criteria andCorpNameIsNotNull() {
            addCriterion("corp_name is not null");
            return (Criteria) this;
        }

        public Criteria andCorpNameEqualTo(String value) {
            addCriterion("corp_name =", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotEqualTo(String value) {
            addCriterion("corp_name <>", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameGreaterThan(String value) {
            addCriterion("corp_name >", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameGreaterThanOrEqualTo(String value) {
            addCriterion("corp_name >=", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameLessThan(String value) {
            addCriterion("corp_name <", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameLessThanOrEqualTo(String value) {
            addCriterion("corp_name <=", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameLike(String value) {
            addCriterion("corp_name like", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotLike(String value) {
            addCriterion("corp_name not like", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameIn(List<String> values) {
            addCriterion("corp_name in", values, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotIn(List<String> values) {
            addCriterion("corp_name not in", values, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameBetween(String value1, String value2) {
            addCriterion("corp_name between", value1, value2, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotBetween(String value1, String value2) {
            addCriterion("corp_name not between", value1, value2, "corpName");
            return (Criteria) this;
        }

        public Criteria andIndustryIsNull() {
            addCriterion("industry is null");
            return (Criteria) this;
        }

        public Criteria andIndustryIsNotNull() {
            addCriterion("industry is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryEqualTo(String value) {
            addCriterion("industry =", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotEqualTo(String value) {
            addCriterion("industry <>", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryGreaterThan(String value) {
            addCriterion("industry >", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryGreaterThanOrEqualTo(String value) {
            addCriterion("industry >=", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLessThan(String value) {
            addCriterion("industry <", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLessThanOrEqualTo(String value) {
            addCriterion("industry <=", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLike(String value) {
            addCriterion("industry like", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotLike(String value) {
            addCriterion("industry not like", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryIn(List<String> values) {
            addCriterion("industry in", values, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotIn(List<String> values) {
            addCriterion("industry not in", values, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryBetween(String value1, String value2) {
            addCriterion("industry between", value1, value2, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotBetween(String value1, String value2) {
            addCriterion("industry not between", value1, value2, "industry");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceIsNull() {
            addCriterion("corp_province is null");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceIsNotNull() {
            addCriterion("corp_province is not null");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceEqualTo(String value) {
            addCriterion("corp_province =", value, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceNotEqualTo(String value) {
            addCriterion("corp_province <>", value, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceGreaterThan(String value) {
            addCriterion("corp_province >", value, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("corp_province >=", value, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceLessThan(String value) {
            addCriterion("corp_province <", value, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceLessThanOrEqualTo(String value) {
            addCriterion("corp_province <=", value, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceLike(String value) {
            addCriterion("corp_province like", value, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceNotLike(String value) {
            addCriterion("corp_province not like", value, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceIn(List<String> values) {
            addCriterion("corp_province in", values, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceNotIn(List<String> values) {
            addCriterion("corp_province not in", values, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceBetween(String value1, String value2) {
            addCriterion("corp_province between", value1, value2, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpProvinceNotBetween(String value1, String value2) {
            addCriterion("corp_province not between", value1, value2, "corpProvince");
            return (Criteria) this;
        }

        public Criteria andCorpCityIsNull() {
            addCriterion("corp_city is null");
            return (Criteria) this;
        }

        public Criteria andCorpCityIsNotNull() {
            addCriterion("corp_city is not null");
            return (Criteria) this;
        }

        public Criteria andCorpCityEqualTo(String value) {
            addCriterion("corp_city =", value, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpCityNotEqualTo(String value) {
            addCriterion("corp_city <>", value, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpCityGreaterThan(String value) {
            addCriterion("corp_city >", value, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpCityGreaterThanOrEqualTo(String value) {
            addCriterion("corp_city >=", value, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpCityLessThan(String value) {
            addCriterion("corp_city <", value, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpCityLessThanOrEqualTo(String value) {
            addCriterion("corp_city <=", value, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpCityLike(String value) {
            addCriterion("corp_city like", value, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpCityNotLike(String value) {
            addCriterion("corp_city not like", value, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpCityIn(List<String> values) {
            addCriterion("corp_city in", values, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpCityNotIn(List<String> values) {
            addCriterion("corp_city not in", values, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpCityBetween(String value1, String value2) {
            addCriterion("corp_city between", value1, value2, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpCityNotBetween(String value1, String value2) {
            addCriterion("corp_city not between", value1, value2, "corpCity");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictIsNull() {
            addCriterion("corp_district is null");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictIsNotNull() {
            addCriterion("corp_district is not null");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictEqualTo(String value) {
            addCriterion("corp_district =", value, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictNotEqualTo(String value) {
            addCriterion("corp_district <>", value, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictGreaterThan(String value) {
            addCriterion("corp_district >", value, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("corp_district >=", value, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictLessThan(String value) {
            addCriterion("corp_district <", value, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictLessThanOrEqualTo(String value) {
            addCriterion("corp_district <=", value, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictLike(String value) {
            addCriterion("corp_district like", value, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictNotLike(String value) {
            addCriterion("corp_district not like", value, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictIn(List<String> values) {
            addCriterion("corp_district in", values, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictNotIn(List<String> values) {
            addCriterion("corp_district not in", values, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictBetween(String value1, String value2) {
            addCriterion("corp_district between", value1, value2, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpDistrictNotBetween(String value1, String value2) {
            addCriterion("corp_district not between", value1, value2, "corpDistrict");
            return (Criteria) this;
        }

        public Criteria andCorpAddressIsNull() {
            addCriterion("corp_address is null");
            return (Criteria) this;
        }

        public Criteria andCorpAddressIsNotNull() {
            addCriterion("corp_address is not null");
            return (Criteria) this;
        }

        public Criteria andCorpAddressEqualTo(String value) {
            addCriterion("corp_address =", value, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andCorpAddressNotEqualTo(String value) {
            addCriterion("corp_address <>", value, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andCorpAddressGreaterThan(String value) {
            addCriterion("corp_address >", value, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andCorpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("corp_address >=", value, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andCorpAddressLessThan(String value) {
            addCriterion("corp_address <", value, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andCorpAddressLessThanOrEqualTo(String value) {
            addCriterion("corp_address <=", value, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andCorpAddressLike(String value) {
            addCriterion("corp_address like", value, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andCorpAddressNotLike(String value) {
            addCriterion("corp_address not like", value, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andCorpAddressIn(List<String> values) {
            addCriterion("corp_address in", values, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andCorpAddressNotIn(List<String> values) {
            addCriterion("corp_address not in", values, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andCorpAddressBetween(String value1, String value2) {
            addCriterion("corp_address between", value1, value2, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andCorpAddressNotBetween(String value1, String value2) {
            addCriterion("corp_address not between", value1, value2, "corpAddress");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("department is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("department is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(String value) {
            addCriterion("department =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(String value) {
            addCriterion("department <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(String value) {
            addCriterion("department >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("department >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(String value) {
            addCriterion("department <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(String value) {
            addCriterion("department <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLike(String value) {
            addCriterion("department like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotLike(String value) {
            addCriterion("department not like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<String> values) {
            addCriterion("department in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<String> values) {
            addCriterion("department not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(String value1, String value2) {
            addCriterion("department between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(String value1, String value2) {
            addCriterion("department not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(String value) {
            addCriterion("position =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            addCriterion("position <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(String value) {
            addCriterion("position >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            addCriterion("position >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(String value) {
            addCriterion("position <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            addCriterion("position <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLike(String value) {
            addCriterion("position like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotLike(String value) {
            addCriterion("position not like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<String> values) {
            addCriterion("position in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<String> values) {
            addCriterion("position not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            addCriterion("position between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            addCriterion("position not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andCorpTelIsNull() {
            addCriterion("corp_tel is null");
            return (Criteria) this;
        }

        public Criteria andCorpTelIsNotNull() {
            addCriterion("corp_tel is not null");
            return (Criteria) this;
        }

        public Criteria andCorpTelEqualTo(String value) {
            addCriterion("corp_tel =", value, "corpTel");
            return (Criteria) this;
        }

        public Criteria andCorpTelNotEqualTo(String value) {
            addCriterion("corp_tel <>", value, "corpTel");
            return (Criteria) this;
        }

        public Criteria andCorpTelGreaterThan(String value) {
            addCriterion("corp_tel >", value, "corpTel");
            return (Criteria) this;
        }

        public Criteria andCorpTelGreaterThanOrEqualTo(String value) {
            addCriterion("corp_tel >=", value, "corpTel");
            return (Criteria) this;
        }

        public Criteria andCorpTelLessThan(String value) {
            addCriterion("corp_tel <", value, "corpTel");
            return (Criteria) this;
        }

        public Criteria andCorpTelLessThanOrEqualTo(String value) {
            addCriterion("corp_tel <=", value, "corpTel");
            return (Criteria) this;
        }

        public Criteria andCorpTelLike(String value) {
            addCriterion("corp_tel like", value, "corpTel");
            return (Criteria) this;
        }

        public Criteria andCorpTelNotLike(String value) {
            addCriterion("corp_tel not like", value, "corpTel");
            return (Criteria) this;
        }

        public Criteria andCorpTelIn(List<String> values) {
            addCriterion("corp_tel in", values, "corpTel");
            return (Criteria) this;
        }

        public Criteria andCorpTelNotIn(List<String> values) {
            addCriterion("corp_tel not in", values, "corpTel");
            return (Criteria) this;
        }

        public Criteria andCorpTelBetween(String value1, String value2) {
            addCriterion("corp_tel between", value1, value2, "corpTel");
            return (Criteria) this;
        }

        public Criteria andCorpTelNotBetween(String value1, String value2) {
            addCriterion("corp_tel not between", value1, value2, "corpTel");
            return (Criteria) this;
        }

        public Criteria andSalaryDayIsNull() {
            addCriterion("salary_day is null");
            return (Criteria) this;
        }

        public Criteria andSalaryDayIsNotNull() {
            addCriterion("salary_day is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryDayEqualTo(String value) {
            addCriterion("salary_day =", value, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryDayNotEqualTo(String value) {
            addCriterion("salary_day <>", value, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryDayGreaterThan(String value) {
            addCriterion("salary_day >", value, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryDayGreaterThanOrEqualTo(String value) {
            addCriterion("salary_day >=", value, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryDayLessThan(String value) {
            addCriterion("salary_day <", value, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryDayLessThanOrEqualTo(String value) {
            addCriterion("salary_day <=", value, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryDayLike(String value) {
            addCriterion("salary_day like", value, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryDayNotLike(String value) {
            addCriterion("salary_day not like", value, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryDayIn(List<String> values) {
            addCriterion("salary_day in", values, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryDayNotIn(List<String> values) {
            addCriterion("salary_day not in", values, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryDayBetween(String value1, String value2) {
            addCriterion("salary_day between", value1, value2, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryDayNotBetween(String value1, String value2) {
            addCriterion("salary_day not between", value1, value2, "salaryDay");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeIsNull() {
            addCriterion("salary_scope is null");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeIsNotNull() {
            addCriterion("salary_scope is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeEqualTo(String value) {
            addCriterion("salary_scope =", value, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeNotEqualTo(String value) {
            addCriterion("salary_scope <>", value, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeGreaterThan(String value) {
            addCriterion("salary_scope >", value, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeGreaterThanOrEqualTo(String value) {
            addCriterion("salary_scope >=", value, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeLessThan(String value) {
            addCriterion("salary_scope <", value, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeLessThanOrEqualTo(String value) {
            addCriterion("salary_scope <=", value, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeLike(String value) {
            addCriterion("salary_scope like", value, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeNotLike(String value) {
            addCriterion("salary_scope not like", value, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeIn(List<String> values) {
            addCriterion("salary_scope in", values, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeNotIn(List<String> values) {
            addCriterion("salary_scope not in", values, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeBetween(String value1, String value2) {
            addCriterion("salary_scope between", value1, value2, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andSalaryScopeNotBetween(String value1, String value2) {
            addCriterion("salary_scope not between", value1, value2, "salaryScope");
            return (Criteria) this;
        }

        public Criteria andCorpEmailIsNull() {
            addCriterion("corp_email is null");
            return (Criteria) this;
        }

        public Criteria andCorpEmailIsNotNull() {
            addCriterion("corp_email is not null");
            return (Criteria) this;
        }

        public Criteria andCorpEmailEqualTo(String value) {
            addCriterion("corp_email =", value, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andCorpEmailNotEqualTo(String value) {
            addCriterion("corp_email <>", value, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andCorpEmailGreaterThan(String value) {
            addCriterion("corp_email >", value, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andCorpEmailGreaterThanOrEqualTo(String value) {
            addCriterion("corp_email >=", value, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andCorpEmailLessThan(String value) {
            addCriterion("corp_email <", value, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andCorpEmailLessThanOrEqualTo(String value) {
            addCriterion("corp_email <=", value, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andCorpEmailLike(String value) {
            addCriterion("corp_email like", value, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andCorpEmailNotLike(String value) {
            addCriterion("corp_email not like", value, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andCorpEmailIn(List<String> values) {
            addCriterion("corp_email in", values, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andCorpEmailNotIn(List<String> values) {
            addCriterion("corp_email not in", values, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andCorpEmailBetween(String value1, String value2) {
            addCriterion("corp_email between", value1, value2, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andCorpEmailNotBetween(String value1, String value2) {
            addCriterion("corp_email not between", value1, value2, "corpEmail");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 13 16:01:18 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_apply_profession
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}