package com.trj.jk.web.domain;

import java.math.BigDecimal;
import java.util.Date;

public class LoanApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.uid
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.apply_id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.product_id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.product_name
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.name
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.mobile
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.amount
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.province
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.city
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.district
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.invitation_code
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String invitationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.tenant
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String tenant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.status
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.step
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private Byte step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.identity_id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String identityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.is_valid
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private Byte isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.vaild_date
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private Date vaildDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.is_manual_audit
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private Byte isManualAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.modify_time
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.create_time
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.type
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.order_no
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_loan_apply.reject_day_info
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    private String rejectDayInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.id
     *
     * @return the value of jk_loan_apply.id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.id
     *
     * @param id the value for jk_loan_apply.id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.uid
     *
     * @return the value of jk_loan_apply.uid
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.uid
     *
     * @param uid the value for jk_loan_apply.uid
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.apply_id
     *
     * @return the value of jk_loan_apply.apply_id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.apply_id
     *
     * @param applyId the value for jk_loan_apply.apply_id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.product_id
     *
     * @return the value of jk_loan_apply.product_id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.product_id
     *
     * @param productId the value for jk_loan_apply.product_id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.product_name
     *
     * @return the value of jk_loan_apply.product_name
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.product_name
     *
     * @param productName the value for jk_loan_apply.product_name
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.name
     *
     * @return the value of jk_loan_apply.name
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.name
     *
     * @param name the value for jk_loan_apply.name
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.mobile
     *
     * @return the value of jk_loan_apply.mobile
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.mobile
     *
     * @param mobile the value for jk_loan_apply.mobile
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.amount
     *
     * @return the value of jk_loan_apply.amount
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.amount
     *
     * @param amount the value for jk_loan_apply.amount
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.province
     *
     * @return the value of jk_loan_apply.province
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.province
     *
     * @param province the value for jk_loan_apply.province
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.city
     *
     * @return the value of jk_loan_apply.city
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.city
     *
     * @param city the value for jk_loan_apply.city
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.district
     *
     * @return the value of jk_loan_apply.district
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.district
     *
     * @param district the value for jk_loan_apply.district
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.invitation_code
     *
     * @return the value of jk_loan_apply.invitation_code
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getInvitationCode() {
        return invitationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.invitation_code
     *
     * @param invitationCode the value for jk_loan_apply.invitation_code
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setInvitationCode(String invitationCode) {
        this.invitationCode = invitationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.tenant
     *
     * @return the value of jk_loan_apply.tenant
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getTenant() {
        return tenant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.tenant
     *
     * @param tenant the value for jk_loan_apply.tenant
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setTenant(String tenant) {
        this.tenant = tenant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.status
     *
     * @return the value of jk_loan_apply.status
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.status
     *
     * @param status the value for jk_loan_apply.status
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.step
     *
     * @return the value of jk_loan_apply.step
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public Byte getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.step
     *
     * @param step the value for jk_loan_apply.step
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setStep(Byte step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.identity_id
     *
     * @return the value of jk_loan_apply.identity_id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.identity_id
     *
     * @param identityId the value for jk_loan_apply.identity_id
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setIdentityId(String identityId) {
        this.identityId = identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.is_valid
     *
     * @return the value of jk_loan_apply.is_valid
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.is_valid
     *
     * @param isValid the value for jk_loan_apply.is_valid
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.vaild_date
     *
     * @return the value of jk_loan_apply.vaild_date
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public Date getVaildDate() {
        return vaildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.vaild_date
     *
     * @param vaildDate the value for jk_loan_apply.vaild_date
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setVaildDate(Date vaildDate) {
        this.vaildDate = vaildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.is_manual_audit
     *
     * @return the value of jk_loan_apply.is_manual_audit
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public Byte getIsManualAudit() {
        return isManualAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.is_manual_audit
     *
     * @param isManualAudit the value for jk_loan_apply.is_manual_audit
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setIsManualAudit(Byte isManualAudit) {
        this.isManualAudit = isManualAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.modify_time
     *
     * @return the value of jk_loan_apply.modify_time
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.modify_time
     *
     * @param modifyTime the value for jk_loan_apply.modify_time
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.create_time
     *
     * @return the value of jk_loan_apply.create_time
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.create_time
     *
     * @param createTime the value for jk_loan_apply.create_time
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.type
     *
     * @return the value of jk_loan_apply.type
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.type
     *
     * @param type the value for jk_loan_apply.type
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.order_no
     *
     * @return the value of jk_loan_apply.order_no
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.order_no
     *
     * @param orderNo the value for jk_loan_apply.order_no
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_loan_apply.reject_day_info
     *
     * @return the value of jk_loan_apply.reject_day_info
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public String getRejectDayInfo() {
        return rejectDayInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_loan_apply.reject_day_info
     *
     * @param rejectDayInfo the value for jk_loan_apply.reject_day_info
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    public void setRejectDayInfo(String rejectDayInfo) {
        this.rejectDayInfo = rejectDayInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LoanApply other = (LoanApply) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getApplyId() == null ? other.getApplyId() == null : this.getApplyId().equals(other.getApplyId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getDistrict() == null ? other.getDistrict() == null : this.getDistrict().equals(other.getDistrict()))
            && (this.getInvitationCode() == null ? other.getInvitationCode() == null : this.getInvitationCode().equals(other.getInvitationCode()))
            && (this.getTenant() == null ? other.getTenant() == null : this.getTenant().equals(other.getTenant()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getStep() == null ? other.getStep() == null : this.getStep().equals(other.getStep()))
            && (this.getIdentityId() == null ? other.getIdentityId() == null : this.getIdentityId().equals(other.getIdentityId()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getVaildDate() == null ? other.getVaildDate() == null : this.getVaildDate().equals(other.getVaildDate()))
            && (this.getIsManualAudit() == null ? other.getIsManualAudit() == null : this.getIsManualAudit().equals(other.getIsManualAudit()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
            && (this.getRejectDayInfo() == null ? other.getRejectDayInfo() == null : this.getRejectDayInfo().equals(other.getRejectDayInfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getApplyId() == null) ? 0 : getApplyId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getDistrict() == null) ? 0 : getDistrict().hashCode());
        result = prime * result + ((getInvitationCode() == null) ? 0 : getInvitationCode().hashCode());
        result = prime * result + ((getTenant() == null) ? 0 : getTenant().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getStep() == null) ? 0 : getStep().hashCode());
        result = prime * result + ((getIdentityId() == null) ? 0 : getIdentityId().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getVaildDate() == null) ? 0 : getVaildDate().hashCode());
        result = prime * result + ((getIsManualAudit() == null) ? 0 : getIsManualAudit().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getRejectDayInfo() == null) ? 0 : getRejectDayInfo().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_apply
     *
     * @mbg.generated Thu Dec 07 11:26:34 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", applyId=").append(applyId);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", name=").append(name);
        sb.append(", mobile=").append(mobile);
        sb.append(", amount=").append(amount);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", invitationCode=").append(invitationCode);
        sb.append(", tenant=").append(tenant);
        sb.append(", status=").append(status);
        sb.append(", step=").append(step);
        sb.append(", identityId=").append(identityId);
        sb.append(", isValid=").append(isValid);
        sb.append(", vaildDate=").append(vaildDate);
        sb.append(", isManualAudit=").append(isManualAudit);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", type=").append(type);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", rejectDayInfo=").append(rejectDayInfo);
        sb.append("]");
        return sb.toString();
    }
}