package com.trj.jk.web.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoanFaceAuthCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public LoanFaceAuthCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNull() {
            addCriterion("apply_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNotNull() {
            addCriterion("apply_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyIdEqualTo(Integer value) {
            addCriterion("apply_id =", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotEqualTo(Integer value) {
            addCriterion("apply_id <>", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThan(Integer value) {
            addCriterion("apply_id >", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_id >=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThan(Integer value) {
            addCriterion("apply_id <", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThanOrEqualTo(Integer value) {
            addCriterion("apply_id <=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdIn(List<Integer> values) {
            addCriterion("apply_id in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotIn(List<Integer> values) {
            addCriterion("apply_id not in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdBetween(Integer value1, Integer value2) {
            addCriterion("apply_id between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_id not between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdIsNull() {
            addCriterion("identity_card_front_image_id is null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdIsNotNull() {
            addCriterion("identity_card_front_image_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdEqualTo(Integer value) {
            addCriterion("identity_card_front_image_id =", value, "identityCardFrontImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdNotEqualTo(Integer value) {
            addCriterion("identity_card_front_image_id <>", value, "identityCardFrontImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdGreaterThan(Integer value) {
            addCriterion("identity_card_front_image_id >", value, "identityCardFrontImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("identity_card_front_image_id >=", value, "identityCardFrontImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdLessThan(Integer value) {
            addCriterion("identity_card_front_image_id <", value, "identityCardFrontImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdLessThanOrEqualTo(Integer value) {
            addCriterion("identity_card_front_image_id <=", value, "identityCardFrontImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdIn(List<Integer> values) {
            addCriterion("identity_card_front_image_id in", values, "identityCardFrontImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdNotIn(List<Integer> values) {
            addCriterion("identity_card_front_image_id not in", values, "identityCardFrontImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdBetween(Integer value1, Integer value2) {
            addCriterion("identity_card_front_image_id between", value1, value2, "identityCardFrontImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardFrontImageIdNotBetween(Integer value1, Integer value2) {
            addCriterion("identity_card_front_image_id not between", value1, value2, "identityCardFrontImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdIsNull() {
            addCriterion("identity_card_opposite_image_id is null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdIsNotNull() {
            addCriterion("identity_card_opposite_image_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdEqualTo(Integer value) {
            addCriterion("identity_card_opposite_image_id =", value, "identityCardOppositeImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdNotEqualTo(Integer value) {
            addCriterion("identity_card_opposite_image_id <>", value, "identityCardOppositeImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdGreaterThan(Integer value) {
            addCriterion("identity_card_opposite_image_id >", value, "identityCardOppositeImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("identity_card_opposite_image_id >=", value, "identityCardOppositeImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdLessThan(Integer value) {
            addCriterion("identity_card_opposite_image_id <", value, "identityCardOppositeImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdLessThanOrEqualTo(Integer value) {
            addCriterion("identity_card_opposite_image_id <=", value, "identityCardOppositeImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdIn(List<Integer> values) {
            addCriterion("identity_card_opposite_image_id in", values, "identityCardOppositeImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdNotIn(List<Integer> values) {
            addCriterion("identity_card_opposite_image_id not in", values, "identityCardOppositeImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdBetween(Integer value1, Integer value2) {
            addCriterion("identity_card_opposite_image_id between", value1, value2, "identityCardOppositeImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityCardOppositeImageIdNotBetween(Integer value1, Integer value2) {
            addCriterion("identity_card_opposite_image_id not between", value1, value2, "identityCardOppositeImageId");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressIsNull() {
            addCriterion("identity_address is null");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressIsNotNull() {
            addCriterion("identity_address is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressEqualTo(String value) {
            addCriterion("identity_address =", value, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressNotEqualTo(String value) {
            addCriterion("identity_address <>", value, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressGreaterThan(String value) {
            addCriterion("identity_address >", value, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressGreaterThanOrEqualTo(String value) {
            addCriterion("identity_address >=", value, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressLessThan(String value) {
            addCriterion("identity_address <", value, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressLessThanOrEqualTo(String value) {
            addCriterion("identity_address <=", value, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressLike(String value) {
            addCriterion("identity_address like", value, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressNotLike(String value) {
            addCriterion("identity_address not like", value, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressIn(List<String> values) {
            addCriterion("identity_address in", values, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressNotIn(List<String> values) {
            addCriterion("identity_address not in", values, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressBetween(String value1, String value2) {
            addCriterion("identity_address between", value1, value2, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andIdentityAddressNotBetween(String value1, String value2) {
            addCriterion("identity_address not between", value1, value2, "identityAddress");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdIsNull() {
            addCriterion("living_body_image_id is null");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdIsNotNull() {
            addCriterion("living_body_image_id is not null");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdEqualTo(Integer value) {
            addCriterion("living_body_image_id =", value, "livingBodyImageId");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdNotEqualTo(Integer value) {
            addCriterion("living_body_image_id <>", value, "livingBodyImageId");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdGreaterThan(Integer value) {
            addCriterion("living_body_image_id >", value, "livingBodyImageId");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("living_body_image_id >=", value, "livingBodyImageId");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdLessThan(Integer value) {
            addCriterion("living_body_image_id <", value, "livingBodyImageId");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdLessThanOrEqualTo(Integer value) {
            addCriterion("living_body_image_id <=", value, "livingBodyImageId");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdIn(List<Integer> values) {
            addCriterion("living_body_image_id in", values, "livingBodyImageId");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdNotIn(List<Integer> values) {
            addCriterion("living_body_image_id not in", values, "livingBodyImageId");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdBetween(Integer value1, Integer value2) {
            addCriterion("living_body_image_id between", value1, value2, "livingBodyImageId");
            return (Criteria) this;
        }

        public Criteria andLivingBodyImageIdNotBetween(Integer value1, Integer value2) {
            addCriterion("living_body_image_id not between", value1, value2, "livingBodyImageId");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdIsNull() {
            addCriterion("head_image_id is null");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdIsNotNull() {
            addCriterion("head_image_id is not null");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdEqualTo(Integer value) {
            addCriterion("head_image_id =", value, "headImageId");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdNotEqualTo(Integer value) {
            addCriterion("head_image_id <>", value, "headImageId");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdGreaterThan(Integer value) {
            addCriterion("head_image_id >", value, "headImageId");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("head_image_id >=", value, "headImageId");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdLessThan(Integer value) {
            addCriterion("head_image_id <", value, "headImageId");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdLessThanOrEqualTo(Integer value) {
            addCriterion("head_image_id <=", value, "headImageId");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdIn(List<Integer> values) {
            addCriterion("head_image_id in", values, "headImageId");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdNotIn(List<Integer> values) {
            addCriterion("head_image_id not in", values, "headImageId");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdBetween(Integer value1, Integer value2) {
            addCriterion("head_image_id between", value1, value2, "headImageId");
            return (Criteria) this;
        }

        public Criteria andHeadImageIdNotBetween(Integer value1, Integer value2) {
            addCriterion("head_image_id not between", value1, value2, "headImageId");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 13 16:01:17 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_face_auth
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}