package com.trj.jk.web.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoanRepayGeneralCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public LoanRepayGeneralCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andPrjIdIsNull() {
            addCriterion("prj_id is null");
            return (Criteria) this;
        }

        public Criteria andPrjIdIsNotNull() {
            addCriterion("prj_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrjIdEqualTo(Integer value) {
            addCriterion("prj_id =", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdNotEqualTo(Integer value) {
            addCriterion("prj_id <>", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdGreaterThan(Integer value) {
            addCriterion("prj_id >", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("prj_id >=", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdLessThan(Integer value) {
            addCriterion("prj_id <", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdLessThanOrEqualTo(Integer value) {
            addCriterion("prj_id <=", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdIn(List<Integer> values) {
            addCriterion("prj_id in", values, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdNotIn(List<Integer> values) {
            addCriterion("prj_id not in", values, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdBetween(Integer value1, Integer value2) {
            addCriterion("prj_id between", value1, value2, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdNotBetween(Integer value1, Integer value2) {
            addCriterion("prj_id not between", value1, value2, "prjId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdIsNull() {
            addCriterion("apply_loan_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdIsNotNull() {
            addCriterion("apply_loan_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdEqualTo(Integer value) {
            addCriterion("apply_loan_id =", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdNotEqualTo(Integer value) {
            addCriterion("apply_loan_id <>", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdGreaterThan(Integer value) {
            addCriterion("apply_loan_id >", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_loan_id >=", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdLessThan(Integer value) {
            addCriterion("apply_loan_id <", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdLessThanOrEqualTo(Integer value) {
            addCriterion("apply_loan_id <=", value, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdIn(List<Integer> values) {
            addCriterion("apply_loan_id in", values, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdNotIn(List<Integer> values) {
            addCriterion("apply_loan_id not in", values, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdBetween(Integer value1, Integer value2) {
            addCriterion("apply_loan_id between", value1, value2, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andApplyLoanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_loan_id not between", value1, value2, "applyLoanId");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdIsNull() {
            addCriterion("loan_limit_id is null");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdIsNotNull() {
            addCriterion("loan_limit_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdEqualTo(Integer value) {
            addCriterion("loan_limit_id =", value, "loanLimitId");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdNotEqualTo(Integer value) {
            addCriterion("loan_limit_id <>", value, "loanLimitId");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdGreaterThan(Integer value) {
            addCriterion("loan_limit_id >", value, "loanLimitId");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_limit_id >=", value, "loanLimitId");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdLessThan(Integer value) {
            addCriterion("loan_limit_id <", value, "loanLimitId");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdLessThanOrEqualTo(Integer value) {
            addCriterion("loan_limit_id <=", value, "loanLimitId");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdIn(List<Integer> values) {
            addCriterion("loan_limit_id in", values, "loanLimitId");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdNotIn(List<Integer> values) {
            addCriterion("loan_limit_id not in", values, "loanLimitId");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdBetween(Integer value1, Integer value2) {
            addCriterion("loan_limit_id between", value1, value2, "loanLimitId");
            return (Criteria) this;
        }

        public Criteria andLoanLimitIdNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_limit_id not between", value1, value2, "loanLimitId");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodIsNull() {
            addCriterion("current_period is null");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodIsNotNull() {
            addCriterion("current_period is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodEqualTo(Byte value) {
            addCriterion("current_period =", value, "currentPeriod");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodNotEqualTo(Byte value) {
            addCriterion("current_period <>", value, "currentPeriod");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodGreaterThan(Byte value) {
            addCriterion("current_period >", value, "currentPeriod");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodGreaterThanOrEqualTo(Byte value) {
            addCriterion("current_period >=", value, "currentPeriod");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodLessThan(Byte value) {
            addCriterion("current_period <", value, "currentPeriod");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodLessThanOrEqualTo(Byte value) {
            addCriterion("current_period <=", value, "currentPeriod");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodIn(List<Byte> values) {
            addCriterion("current_period in", values, "currentPeriod");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodNotIn(List<Byte> values) {
            addCriterion("current_period not in", values, "currentPeriod");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodBetween(Byte value1, Byte value2) {
            addCriterion("current_period between", value1, value2, "currentPeriod");
            return (Criteria) this;
        }

        public Criteria andCurrentPeriodNotBetween(Byte value1, Byte value2) {
            addCriterion("current_period not between", value1, value2, "currentPeriod");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusIsNull() {
            addCriterion("repay_error_status is null");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusIsNotNull() {
            addCriterion("repay_error_status is not null");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusEqualTo(Byte value) {
            addCriterion("repay_error_status =", value, "repayErrorStatus");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusNotEqualTo(Byte value) {
            addCriterion("repay_error_status <>", value, "repayErrorStatus");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusGreaterThan(Byte value) {
            addCriterion("repay_error_status >", value, "repayErrorStatus");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("repay_error_status >=", value, "repayErrorStatus");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusLessThan(Byte value) {
            addCriterion("repay_error_status <", value, "repayErrorStatus");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusLessThanOrEqualTo(Byte value) {
            addCriterion("repay_error_status <=", value, "repayErrorStatus");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusIn(List<Byte> values) {
            addCriterion("repay_error_status in", values, "repayErrorStatus");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusNotIn(List<Byte> values) {
            addCriterion("repay_error_status not in", values, "repayErrorStatus");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusBetween(Byte value1, Byte value2) {
            addCriterion("repay_error_status between", value1, value2, "repayErrorStatus");
            return (Criteria) this;
        }

        public Criteria andRepayErrorStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("repay_error_status not between", value1, value2, "repayErrorStatus");
            return (Criteria) this;
        }

        public Criteria andRepayDayIsNull() {
            addCriterion("repay_day is null");
            return (Criteria) this;
        }

        public Criteria andRepayDayIsNotNull() {
            addCriterion("repay_day is not null");
            return (Criteria) this;
        }

        public Criteria andRepayDayEqualTo(Byte value) {
            addCriterion("repay_day =", value, "repayDay");
            return (Criteria) this;
        }

        public Criteria andRepayDayNotEqualTo(Byte value) {
            addCriterion("repay_day <>", value, "repayDay");
            return (Criteria) this;
        }

        public Criteria andRepayDayGreaterThan(Byte value) {
            addCriterion("repay_day >", value, "repayDay");
            return (Criteria) this;
        }

        public Criteria andRepayDayGreaterThanOrEqualTo(Byte value) {
            addCriterion("repay_day >=", value, "repayDay");
            return (Criteria) this;
        }

        public Criteria andRepayDayLessThan(Byte value) {
            addCriterion("repay_day <", value, "repayDay");
            return (Criteria) this;
        }

        public Criteria andRepayDayLessThanOrEqualTo(Byte value) {
            addCriterion("repay_day <=", value, "repayDay");
            return (Criteria) this;
        }

        public Criteria andRepayDayIn(List<Byte> values) {
            addCriterion("repay_day in", values, "repayDay");
            return (Criteria) this;
        }

        public Criteria andRepayDayNotIn(List<Byte> values) {
            addCriterion("repay_day not in", values, "repayDay");
            return (Criteria) this;
        }

        public Criteria andRepayDayBetween(Byte value1, Byte value2) {
            addCriterion("repay_day between", value1, value2, "repayDay");
            return (Criteria) this;
        }

        public Criteria andRepayDayNotBetween(Byte value1, Byte value2) {
            addCriterion("repay_day not between", value1, value2, "repayDay");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andRestAmountIsNull() {
            addCriterion("rest_amount is null");
            return (Criteria) this;
        }

        public Criteria andRestAmountIsNotNull() {
            addCriterion("rest_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRestAmountEqualTo(BigDecimal value) {
            addCriterion("rest_amount =", value, "restAmount");
            return (Criteria) this;
        }

        public Criteria andRestAmountNotEqualTo(BigDecimal value) {
            addCriterion("rest_amount <>", value, "restAmount");
            return (Criteria) this;
        }

        public Criteria andRestAmountGreaterThan(BigDecimal value) {
            addCriterion("rest_amount >", value, "restAmount");
            return (Criteria) this;
        }

        public Criteria andRestAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rest_amount >=", value, "restAmount");
            return (Criteria) this;
        }

        public Criteria andRestAmountLessThan(BigDecimal value) {
            addCriterion("rest_amount <", value, "restAmount");
            return (Criteria) this;
        }

        public Criteria andRestAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rest_amount <=", value, "restAmount");
            return (Criteria) this;
        }

        public Criteria andRestAmountIn(List<BigDecimal> values) {
            addCriterion("rest_amount in", values, "restAmount");
            return (Criteria) this;
        }

        public Criteria andRestAmountNotIn(List<BigDecimal> values) {
            addCriterion("rest_amount not in", values, "restAmount");
            return (Criteria) this;
        }

        public Criteria andRestAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rest_amount between", value1, value2, "restAmount");
            return (Criteria) this;
        }

        public Criteria andRestAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rest_amount not between", value1, value2, "restAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountIsNull() {
            addCriterion("repayed_amount is null");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountIsNotNull() {
            addCriterion("repayed_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountEqualTo(BigDecimal value) {
            addCriterion("repayed_amount =", value, "repayedAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountNotEqualTo(BigDecimal value) {
            addCriterion("repayed_amount <>", value, "repayedAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountGreaterThan(BigDecimal value) {
            addCriterion("repayed_amount >", value, "repayedAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("repayed_amount >=", value, "repayedAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountLessThan(BigDecimal value) {
            addCriterion("repayed_amount <", value, "repayedAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("repayed_amount <=", value, "repayedAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountIn(List<BigDecimal> values) {
            addCriterion("repayed_amount in", values, "repayedAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountNotIn(List<BigDecimal> values) {
            addCriterion("repayed_amount not in", values, "repayedAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repayed_amount between", value1, value2, "repayedAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repayed_amount not between", value1, value2, "repayedAmount");
            return (Criteria) this;
        }

        public Criteria andPrincipalIsNull() {
            addCriterion("principal is null");
            return (Criteria) this;
        }

        public Criteria andPrincipalIsNotNull() {
            addCriterion("principal is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipalEqualTo(BigDecimal value) {
            addCriterion("principal =", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalNotEqualTo(BigDecimal value) {
            addCriterion("principal <>", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalGreaterThan(BigDecimal value) {
            addCriterion("principal >", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("principal >=", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalLessThan(BigDecimal value) {
            addCriterion("principal <", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("principal <=", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalIn(List<BigDecimal> values) {
            addCriterion("principal in", values, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalNotIn(List<BigDecimal> values) {
            addCriterion("principal not in", values, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("principal between", value1, value2, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("principal not between", value1, value2, "principal");
            return (Criteria) this;
        }

        public Criteria andInterestIsNull() {
            addCriterion("interest is null");
            return (Criteria) this;
        }

        public Criteria andInterestIsNotNull() {
            addCriterion("interest is not null");
            return (Criteria) this;
        }

        public Criteria andInterestEqualTo(BigDecimal value) {
            addCriterion("interest =", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotEqualTo(BigDecimal value) {
            addCriterion("interest <>", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThan(BigDecimal value) {
            addCriterion("interest >", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("interest >=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThan(BigDecimal value) {
            addCriterion("interest <", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThanOrEqualTo(BigDecimal value) {
            addCriterion("interest <=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestIn(List<BigDecimal> values) {
            addCriterion("interest in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotIn(List<BigDecimal> values) {
            addCriterion("interest not in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest not between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeIsNull() {
            addCriterion("commission_charge is null");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeIsNotNull() {
            addCriterion("commission_charge is not null");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeEqualTo(BigDecimal value) {
            addCriterion("commission_charge =", value, "commissionCharge");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeNotEqualTo(BigDecimal value) {
            addCriterion("commission_charge <>", value, "commissionCharge");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeGreaterThan(BigDecimal value) {
            addCriterion("commission_charge >", value, "commissionCharge");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("commission_charge >=", value, "commissionCharge");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeLessThan(BigDecimal value) {
            addCriterion("commission_charge <", value, "commissionCharge");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("commission_charge <=", value, "commissionCharge");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeIn(List<BigDecimal> values) {
            addCriterion("commission_charge in", values, "commissionCharge");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeNotIn(List<BigDecimal> values) {
            addCriterion("commission_charge not in", values, "commissionCharge");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("commission_charge between", value1, value2, "commissionCharge");
            return (Criteria) this;
        }

        public Criteria andCommissionChargeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("commission_charge not between", value1, value2, "commissionCharge");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountIsNull() {
            addCriterion("penalty_interest_amount is null");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountIsNotNull() {
            addCriterion("penalty_interest_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountEqualTo(BigDecimal value) {
            addCriterion("penalty_interest_amount =", value, "penaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountNotEqualTo(BigDecimal value) {
            addCriterion("penalty_interest_amount <>", value, "penaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountGreaterThan(BigDecimal value) {
            addCriterion("penalty_interest_amount >", value, "penaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("penalty_interest_amount >=", value, "penaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountLessThan(BigDecimal value) {
            addCriterion("penalty_interest_amount <", value, "penaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("penalty_interest_amount <=", value, "penaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountIn(List<BigDecimal> values) {
            addCriterion("penalty_interest_amount in", values, "penaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountNotIn(List<BigDecimal> values) {
            addCriterion("penalty_interest_amount not in", values, "penaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("penalty_interest_amount between", value1, value2, "penaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andPenaltyInterestAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("penalty_interest_amount not between", value1, value2, "penaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountIsNull() {
            addCriterion("this_period_amount is null");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountIsNotNull() {
            addCriterion("this_period_amount is not null");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountEqualTo(BigDecimal value) {
            addCriterion("this_period_amount =", value, "thisPeriodAmount");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountNotEqualTo(BigDecimal value) {
            addCriterion("this_period_amount <>", value, "thisPeriodAmount");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountGreaterThan(BigDecimal value) {
            addCriterion("this_period_amount >", value, "thisPeriodAmount");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("this_period_amount >=", value, "thisPeriodAmount");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountLessThan(BigDecimal value) {
            addCriterion("this_period_amount <", value, "thisPeriodAmount");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("this_period_amount <=", value, "thisPeriodAmount");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountIn(List<BigDecimal> values) {
            addCriterion("this_period_amount in", values, "thisPeriodAmount");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountNotIn(List<BigDecimal> values) {
            addCriterion("this_period_amount not in", values, "thisPeriodAmount");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("this_period_amount between", value1, value2, "thisPeriodAmount");
            return (Criteria) this;
        }

        public Criteria andThisPeriodAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("this_period_amount not between", value1, value2, "thisPeriodAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountIsNull() {
            addCriterion("overdue_amount is null");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountIsNotNull() {
            addCriterion("overdue_amount is not null");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountEqualTo(BigDecimal value) {
            addCriterion("overdue_amount =", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountNotEqualTo(BigDecimal value) {
            addCriterion("overdue_amount <>", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountGreaterThan(BigDecimal value) {
            addCriterion("overdue_amount >", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("overdue_amount >=", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountLessThan(BigDecimal value) {
            addCriterion("overdue_amount <", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("overdue_amount <=", value, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountIn(List<BigDecimal> values) {
            addCriterion("overdue_amount in", values, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountNotIn(List<BigDecimal> values) {
            addCriterion("overdue_amount not in", values, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("overdue_amount between", value1, value2, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverdueAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("overdue_amount not between", value1, value2, "overdueAmount");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsIsNull() {
            addCriterion("overdue_periods is null");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsIsNotNull() {
            addCriterion("overdue_periods is not null");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsEqualTo(String value) {
            addCriterion("overdue_periods =", value, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsNotEqualTo(String value) {
            addCriterion("overdue_periods <>", value, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsGreaterThan(String value) {
            addCriterion("overdue_periods >", value, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsGreaterThanOrEqualTo(String value) {
            addCriterion("overdue_periods >=", value, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsLessThan(String value) {
            addCriterion("overdue_periods <", value, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsLessThanOrEqualTo(String value) {
            addCriterion("overdue_periods <=", value, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsLike(String value) {
            addCriterion("overdue_periods like", value, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsNotLike(String value) {
            addCriterion("overdue_periods not like", value, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsIn(List<String> values) {
            addCriterion("overdue_periods in", values, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsNotIn(List<String> values) {
            addCriterion("overdue_periods not in", values, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsBetween(String value1, String value2) {
            addCriterion("overdue_periods between", value1, value2, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andOverduePeriodsNotBetween(String value1, String value2) {
            addCriterion("overdue_periods not between", value1, value2, "overduePeriods");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalIsNull() {
            addCriterion("repayed_principal is null");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalIsNotNull() {
            addCriterion("repayed_principal is not null");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalEqualTo(BigDecimal value) {
            addCriterion("repayed_principal =", value, "repayedPrincipal");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalNotEqualTo(BigDecimal value) {
            addCriterion("repayed_principal <>", value, "repayedPrincipal");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalGreaterThan(BigDecimal value) {
            addCriterion("repayed_principal >", value, "repayedPrincipal");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("repayed_principal >=", value, "repayedPrincipal");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalLessThan(BigDecimal value) {
            addCriterion("repayed_principal <", value, "repayedPrincipal");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("repayed_principal <=", value, "repayedPrincipal");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalIn(List<BigDecimal> values) {
            addCriterion("repayed_principal in", values, "repayedPrincipal");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalNotIn(List<BigDecimal> values) {
            addCriterion("repayed_principal not in", values, "repayedPrincipal");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repayed_principal between", value1, value2, "repayedPrincipal");
            return (Criteria) this;
        }

        public Criteria andRepayedPrincipalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repayed_principal not between", value1, value2, "repayedPrincipal");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalIsNull() {
            addCriterion("rest_principal is null");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalIsNotNull() {
            addCriterion("rest_principal is not null");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalEqualTo(BigDecimal value) {
            addCriterion("rest_principal =", value, "restPrincipal");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalNotEqualTo(BigDecimal value) {
            addCriterion("rest_principal <>", value, "restPrincipal");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalGreaterThan(BigDecimal value) {
            addCriterion("rest_principal >", value, "restPrincipal");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rest_principal >=", value, "restPrincipal");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalLessThan(BigDecimal value) {
            addCriterion("rest_principal <", value, "restPrincipal");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rest_principal <=", value, "restPrincipal");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalIn(List<BigDecimal> values) {
            addCriterion("rest_principal in", values, "restPrincipal");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalNotIn(List<BigDecimal> values) {
            addCriterion("rest_principal not in", values, "restPrincipal");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rest_principal between", value1, value2, "restPrincipal");
            return (Criteria) this;
        }

        public Criteria andRestPrincipalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rest_principal not between", value1, value2, "restPrincipal");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountIsNull() {
            addCriterion("repayed_penalty_interest_amount is null");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountIsNotNull() {
            addCriterion("repayed_penalty_interest_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountEqualTo(BigDecimal value) {
            addCriterion("repayed_penalty_interest_amount =", value, "repayedPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountNotEqualTo(BigDecimal value) {
            addCriterion("repayed_penalty_interest_amount <>", value, "repayedPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountGreaterThan(BigDecimal value) {
            addCriterion("repayed_penalty_interest_amount >", value, "repayedPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("repayed_penalty_interest_amount >=", value, "repayedPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountLessThan(BigDecimal value) {
            addCriterion("repayed_penalty_interest_amount <", value, "repayedPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("repayed_penalty_interest_amount <=", value, "repayedPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountIn(List<BigDecimal> values) {
            addCriterion("repayed_penalty_interest_amount in", values, "repayedPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountNotIn(List<BigDecimal> values) {
            addCriterion("repayed_penalty_interest_amount not in", values, "repayedPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repayed_penalty_interest_amount between", value1, value2, "repayedPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRepayedPenaltyInterestAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repayed_penalty_interest_amount not between", value1, value2, "repayedPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountIsNull() {
            addCriterion("rest_penalty_interest_amount is null");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountIsNotNull() {
            addCriterion("rest_penalty_interest_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountEqualTo(BigDecimal value) {
            addCriterion("rest_penalty_interest_amount =", value, "restPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountNotEqualTo(BigDecimal value) {
            addCriterion("rest_penalty_interest_amount <>", value, "restPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountGreaterThan(BigDecimal value) {
            addCriterion("rest_penalty_interest_amount >", value, "restPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rest_penalty_interest_amount >=", value, "restPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountLessThan(BigDecimal value) {
            addCriterion("rest_penalty_interest_amount <", value, "restPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rest_penalty_interest_amount <=", value, "restPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountIn(List<BigDecimal> values) {
            addCriterion("rest_penalty_interest_amount in", values, "restPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountNotIn(List<BigDecimal> values) {
            addCriterion("rest_penalty_interest_amount not in", values, "restPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rest_penalty_interest_amount between", value1, value2, "restPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andRestPenaltyInterestAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rest_penalty_interest_amount not between", value1, value2, "restPenaltyInterestAmount");
            return (Criteria) this;
        }

        public Criteria andYearRateIsNull() {
            addCriterion("year_rate is null");
            return (Criteria) this;
        }

        public Criteria andYearRateIsNotNull() {
            addCriterion("year_rate is not null");
            return (Criteria) this;
        }

        public Criteria andYearRateEqualTo(BigDecimal value) {
            addCriterion("year_rate =", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateNotEqualTo(BigDecimal value) {
            addCriterion("year_rate <>", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateGreaterThan(BigDecimal value) {
            addCriterion("year_rate >", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("year_rate >=", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateLessThan(BigDecimal value) {
            addCriterion("year_rate <", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("year_rate <=", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateIn(List<BigDecimal> values) {
            addCriterion("year_rate in", values, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateNotIn(List<BigDecimal> values) {
            addCriterion("year_rate not in", values, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("year_rate between", value1, value2, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("year_rate not between", value1, value2, "yearRate");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 13 16:01:17 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jk_loan_repay_general
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}