package com.trj.jk.web.domain;

import java.util.Date;

public class MobileLocationInterval {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.id
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.uid
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.loan_apply_id
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private Integer loanApplyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.app_system
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private String appSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.collect_node
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private Byte collectNode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.mobile
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.latitude
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.longitude
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.province
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.city
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.district
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.ip
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.is_proxy
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private Byte isProxy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.modify_time
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_mobile_location_interval.create_time
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.id
     *
     * @return the value of jk_mobile_location_interval.id
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.id
     *
     * @param id the value for jk_mobile_location_interval.id
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.uid
     *
     * @return the value of jk_mobile_location_interval.uid
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.uid
     *
     * @param uid the value for jk_mobile_location_interval.uid
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.loan_apply_id
     *
     * @return the value of jk_mobile_location_interval.loan_apply_id
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public Integer getLoanApplyId() {
        return loanApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.loan_apply_id
     *
     * @param loanApplyId the value for jk_mobile_location_interval.loan_apply_id
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setLoanApplyId(Integer loanApplyId) {
        this.loanApplyId = loanApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.app_system
     *
     * @return the value of jk_mobile_location_interval.app_system
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public String getAppSystem() {
        return appSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.app_system
     *
     * @param appSystem the value for jk_mobile_location_interval.app_system
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setAppSystem(String appSystem) {
        this.appSystem = appSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.collect_node
     *
     * @return the value of jk_mobile_location_interval.collect_node
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public Byte getCollectNode() {
        return collectNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.collect_node
     *
     * @param collectNode the value for jk_mobile_location_interval.collect_node
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setCollectNode(Byte collectNode) {
        this.collectNode = collectNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.mobile
     *
     * @return the value of jk_mobile_location_interval.mobile
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.mobile
     *
     * @param mobile the value for jk_mobile_location_interval.mobile
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.latitude
     *
     * @return the value of jk_mobile_location_interval.latitude
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.latitude
     *
     * @param latitude the value for jk_mobile_location_interval.latitude
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.longitude
     *
     * @return the value of jk_mobile_location_interval.longitude
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.longitude
     *
     * @param longitude the value for jk_mobile_location_interval.longitude
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.province
     *
     * @return the value of jk_mobile_location_interval.province
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.province
     *
     * @param province the value for jk_mobile_location_interval.province
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.city
     *
     * @return the value of jk_mobile_location_interval.city
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.city
     *
     * @param city the value for jk_mobile_location_interval.city
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.district
     *
     * @return the value of jk_mobile_location_interval.district
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.district
     *
     * @param district the value for jk_mobile_location_interval.district
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.ip
     *
     * @return the value of jk_mobile_location_interval.ip
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.ip
     *
     * @param ip the value for jk_mobile_location_interval.ip
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.is_proxy
     *
     * @return the value of jk_mobile_location_interval.is_proxy
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public Byte getIsProxy() {
        return isProxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.is_proxy
     *
     * @param isProxy the value for jk_mobile_location_interval.is_proxy
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setIsProxy(Byte isProxy) {
        this.isProxy = isProxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.modify_time
     *
     * @return the value of jk_mobile_location_interval.modify_time
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.modify_time
     *
     * @param modifyTime the value for jk_mobile_location_interval.modify_time
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_mobile_location_interval.create_time
     *
     * @return the value of jk_mobile_location_interval.create_time
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_mobile_location_interval.create_time
     *
     * @param createTime the value for jk_mobile_location_interval.create_time
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_mobile_location_interval
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MobileLocationInterval other = (MobileLocationInterval) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getLoanApplyId() == null ? other.getLoanApplyId() == null : this.getLoanApplyId().equals(other.getLoanApplyId()))
            && (this.getAppSystem() == null ? other.getAppSystem() == null : this.getAppSystem().equals(other.getAppSystem()))
            && (this.getCollectNode() == null ? other.getCollectNode() == null : this.getCollectNode().equals(other.getCollectNode()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getDistrict() == null ? other.getDistrict() == null : this.getDistrict().equals(other.getDistrict()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getIsProxy() == null ? other.getIsProxy() == null : this.getIsProxy().equals(other.getIsProxy()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_mobile_location_interval
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getLoanApplyId() == null) ? 0 : getLoanApplyId().hashCode());
        result = prime * result + ((getAppSystem() == null) ? 0 : getAppSystem().hashCode());
        result = prime * result + ((getCollectNode() == null) ? 0 : getCollectNode().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getDistrict() == null) ? 0 : getDistrict().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getIsProxy() == null) ? 0 : getIsProxy().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_mobile_location_interval
     *
     * @mbg.generated Tue Jun 13 16:01:18 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", loanApplyId=").append(loanApplyId);
        sb.append(", appSystem=").append(appSystem);
        sb.append(", collectNode=").append(collectNode);
        sb.append(", mobile=").append(mobile);
        sb.append(", latitude=").append(latitude);
        sb.append(", longitude=").append(longitude);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", ip=").append(ip);
        sb.append(", isProxy=").append(isProxy);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}