package com.trj.jk.web.domain;

public class RefGeocode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.district_full_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String districtFullCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.country_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String countryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.country_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String countryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.province_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.province_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.city_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.city_full_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String cityFullCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.city_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.district_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String districtCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.district_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String districtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.ctime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_ref_geocode.mtime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.id
     *
     * @return the value of jk_ref_geocode.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.id
     *
     * @param id the value for jk_ref_geocode.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.district_full_code
     *
     * @return the value of jk_ref_geocode.district_full_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getDistrictFullCode() {
        return districtFullCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.district_full_code
     *
     * @param districtFullCode the value for jk_ref_geocode.district_full_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setDistrictFullCode(String districtFullCode) {
        this.districtFullCode = districtFullCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.country_code
     *
     * @return the value of jk_ref_geocode.country_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.country_code
     *
     * @param countryCode the value for jk_ref_geocode.country_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.country_name
     *
     * @return the value of jk_ref_geocode.country_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.country_name
     *
     * @param countryName the value for jk_ref_geocode.country_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.province_code
     *
     * @return the value of jk_ref_geocode.province_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.province_code
     *
     * @param provinceCode the value for jk_ref_geocode.province_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.province_name
     *
     * @return the value of jk_ref_geocode.province_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.province_name
     *
     * @param provinceName the value for jk_ref_geocode.province_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.city_code
     *
     * @return the value of jk_ref_geocode.city_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.city_code
     *
     * @param cityCode the value for jk_ref_geocode.city_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.city_full_code
     *
     * @return the value of jk_ref_geocode.city_full_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getCityFullCode() {
        return cityFullCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.city_full_code
     *
     * @param cityFullCode the value for jk_ref_geocode.city_full_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCityFullCode(String cityFullCode) {
        this.cityFullCode = cityFullCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.city_name
     *
     * @return the value of jk_ref_geocode.city_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.city_name
     *
     * @param cityName the value for jk_ref_geocode.city_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.district_code
     *
     * @return the value of jk_ref_geocode.district_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.district_code
     *
     * @param districtCode the value for jk_ref_geocode.district_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.district_name
     *
     * @return the value of jk_ref_geocode.district_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.district_name
     *
     * @param districtName the value for jk_ref_geocode.district_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.ctime
     *
     * @return the value of jk_ref_geocode.ctime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.ctime
     *
     * @param ctime the value for jk_ref_geocode.ctime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCtime(String ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_ref_geocode.mtime
     *
     * @return the value of jk_ref_geocode.mtime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_ref_geocode.mtime
     *
     * @param mtime the value for jk_ref_geocode.mtime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setMtime(String mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_ref_geocode
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RefGeocode other = (RefGeocode) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDistrictFullCode() == null ? other.getDistrictFullCode() == null : this.getDistrictFullCode().equals(other.getDistrictFullCode()))
            && (this.getCountryCode() == null ? other.getCountryCode() == null : this.getCountryCode().equals(other.getCountryCode()))
            && (this.getCountryName() == null ? other.getCountryName() == null : this.getCountryName().equals(other.getCountryName()))
            && (this.getProvinceCode() == null ? other.getProvinceCode() == null : this.getProvinceCode().equals(other.getProvinceCode()))
            && (this.getProvinceName() == null ? other.getProvinceName() == null : this.getProvinceName().equals(other.getProvinceName()))
            && (this.getCityCode() == null ? other.getCityCode() == null : this.getCityCode().equals(other.getCityCode()))
            && (this.getCityFullCode() == null ? other.getCityFullCode() == null : this.getCityFullCode().equals(other.getCityFullCode()))
            && (this.getCityName() == null ? other.getCityName() == null : this.getCityName().equals(other.getCityName()))
            && (this.getDistrictCode() == null ? other.getDistrictCode() == null : this.getDistrictCode().equals(other.getDistrictCode()))
            && (this.getDistrictName() == null ? other.getDistrictName() == null : this.getDistrictName().equals(other.getDistrictName()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()))
            && (this.getMtime() == null ? other.getMtime() == null : this.getMtime().equals(other.getMtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_ref_geocode
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDistrictFullCode() == null) ? 0 : getDistrictFullCode().hashCode());
        result = prime * result + ((getCountryCode() == null) ? 0 : getCountryCode().hashCode());
        result = prime * result + ((getCountryName() == null) ? 0 : getCountryName().hashCode());
        result = prime * result + ((getProvinceCode() == null) ? 0 : getProvinceCode().hashCode());
        result = prime * result + ((getProvinceName() == null) ? 0 : getProvinceName().hashCode());
        result = prime * result + ((getCityCode() == null) ? 0 : getCityCode().hashCode());
        result = prime * result + ((getCityFullCode() == null) ? 0 : getCityFullCode().hashCode());
        result = prime * result + ((getCityName() == null) ? 0 : getCityName().hashCode());
        result = prime * result + ((getDistrictCode() == null) ? 0 : getDistrictCode().hashCode());
        result = prime * result + ((getDistrictName() == null) ? 0 : getDistrictName().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        result = prime * result + ((getMtime() == null) ? 0 : getMtime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_ref_geocode
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", districtFullCode=").append(districtFullCode);
        sb.append(", countryCode=").append(countryCode);
        sb.append(", countryName=").append(countryName);
        sb.append(", provinceCode=").append(provinceCode);
        sb.append(", provinceName=").append(provinceName);
        sb.append(", cityCode=").append(cityCode);
        sb.append(", cityFullCode=").append(cityFullCode);
        sb.append(", cityName=").append(cityName);
        sb.append(", districtCode=").append(districtCode);
        sb.append(", districtName=").append(districtName);
        sb.append(", ctime=").append(ctime);
        sb.append(", mtime=").append(mtime);
        sb.append("]");
        return sb.toString();
    }
}