package com.trj.jk.web.domain;

public class ThirdpartyRequestResponseLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_thirdparty_request_response_log.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_thirdparty_request_response_log.uid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_thirdparty_request_response_log.request_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Byte requestType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_thirdparty_request_response_log.thirdparty_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String thirdpartyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_thirdparty_request_response_log.request_source
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Boolean requestSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_thirdparty_request_response_log.request_info
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String requestInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_thirdparty_request_response_log.response_info
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String responseInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_thirdparty_request_response_log.ref_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String refId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_thirdparty_request_response_log.remark
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_thirdparty_request_response_log.mtime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Integer mtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_thirdparty_request_response_log.ctime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Integer ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_thirdparty_request_response_log.id
     *
     * @return the value of jk_thirdparty_request_response_log.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_thirdparty_request_response_log.id
     *
     * @param id the value for jk_thirdparty_request_response_log.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_thirdparty_request_response_log.uid
     *
     * @return the value of jk_thirdparty_request_response_log.uid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_thirdparty_request_response_log.uid
     *
     * @param uid the value for jk_thirdparty_request_response_log.uid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_thirdparty_request_response_log.request_type
     *
     * @return the value of jk_thirdparty_request_response_log.request_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Byte getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_thirdparty_request_response_log.request_type
     *
     * @param requestType the value for jk_thirdparty_request_response_log.request_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setRequestType(Byte requestType) {
        this.requestType = requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_thirdparty_request_response_log.thirdparty_name
     *
     * @return the value of jk_thirdparty_request_response_log.thirdparty_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getThirdpartyName() {
        return thirdpartyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_thirdparty_request_response_log.thirdparty_name
     *
     * @param thirdpartyName the value for jk_thirdparty_request_response_log.thirdparty_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setThirdpartyName(String thirdpartyName) {
        this.thirdpartyName = thirdpartyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_thirdparty_request_response_log.request_source
     *
     * @return the value of jk_thirdparty_request_response_log.request_source
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Boolean getRequestSource() {
        return requestSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_thirdparty_request_response_log.request_source
     *
     * @param requestSource the value for jk_thirdparty_request_response_log.request_source
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setRequestSource(Boolean requestSource) {
        this.requestSource = requestSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_thirdparty_request_response_log.request_info
     *
     * @return the value of jk_thirdparty_request_response_log.request_info
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getRequestInfo() {
        return requestInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_thirdparty_request_response_log.request_info
     *
     * @param requestInfo the value for jk_thirdparty_request_response_log.request_info
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setRequestInfo(String requestInfo) {
        this.requestInfo = requestInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_thirdparty_request_response_log.response_info
     *
     * @return the value of jk_thirdparty_request_response_log.response_info
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getResponseInfo() {
        return responseInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_thirdparty_request_response_log.response_info
     *
     * @param responseInfo the value for jk_thirdparty_request_response_log.response_info
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setResponseInfo(String responseInfo) {
        this.responseInfo = responseInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_thirdparty_request_response_log.ref_id
     *
     * @return the value of jk_thirdparty_request_response_log.ref_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_thirdparty_request_response_log.ref_id
     *
     * @param refId the value for jk_thirdparty_request_response_log.ref_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setRefId(String refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_thirdparty_request_response_log.remark
     *
     * @return the value of jk_thirdparty_request_response_log.remark
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_thirdparty_request_response_log.remark
     *
     * @param remark the value for jk_thirdparty_request_response_log.remark
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_thirdparty_request_response_log.mtime
     *
     * @return the value of jk_thirdparty_request_response_log.mtime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Integer getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_thirdparty_request_response_log.mtime
     *
     * @param mtime the value for jk_thirdparty_request_response_log.mtime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_thirdparty_request_response_log.ctime
     *
     * @return the value of jk_thirdparty_request_response_log.ctime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_thirdparty_request_response_log.ctime
     *
     * @param ctime the value for jk_thirdparty_request_response_log.ctime
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_thirdparty_request_response_log
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ThirdpartyRequestResponseLog other = (ThirdpartyRequestResponseLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getRequestType() == null ? other.getRequestType() == null : this.getRequestType().equals(other.getRequestType()))
            && (this.getThirdpartyName() == null ? other.getThirdpartyName() == null : this.getThirdpartyName().equals(other.getThirdpartyName()))
            && (this.getRequestSource() == null ? other.getRequestSource() == null : this.getRequestSource().equals(other.getRequestSource()))
            && (this.getRequestInfo() == null ? other.getRequestInfo() == null : this.getRequestInfo().equals(other.getRequestInfo()))
            && (this.getResponseInfo() == null ? other.getResponseInfo() == null : this.getResponseInfo().equals(other.getResponseInfo()))
            && (this.getRefId() == null ? other.getRefId() == null : this.getRefId().equals(other.getRefId()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getMtime() == null ? other.getMtime() == null : this.getMtime().equals(other.getMtime()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_thirdparty_request_response_log
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getRequestType() == null) ? 0 : getRequestType().hashCode());
        result = prime * result + ((getThirdpartyName() == null) ? 0 : getThirdpartyName().hashCode());
        result = prime * result + ((getRequestSource() == null) ? 0 : getRequestSource().hashCode());
        result = prime * result + ((getRequestInfo() == null) ? 0 : getRequestInfo().hashCode());
        result = prime * result + ((getResponseInfo() == null) ? 0 : getResponseInfo().hashCode());
        result = prime * result + ((getRefId() == null) ? 0 : getRefId().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getMtime() == null) ? 0 : getMtime().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_thirdparty_request_response_log
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", requestType=").append(requestType);
        sb.append(", thirdpartyName=").append(thirdpartyName);
        sb.append(", requestSource=").append(requestSource);
        sb.append(", requestInfo=").append(requestInfo);
        sb.append(", responseInfo=").append(responseInfo);
        sb.append(", refId=").append(refId);
        sb.append(", remark=").append(remark);
        sb.append(", mtime=").append(mtime);
        sb.append(", ctime=").append(ctime);
        sb.append("]");
        return sb.toString();
    }
}