package com.trj.jk.web.domain;

import java.util.Date;

public class UserBankCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.uid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.media_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String mediaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.media_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String mediaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.mer_cust_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String merCustId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.bank_card_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String bankCardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.card_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.identity_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String identityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.identity_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String identityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.card_holder
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String cardHolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.bind_no
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String bindNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.usr_pay_agreement_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String usrPayAgreementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.usr_busi_agreement_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String usrBusiAgreementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.gate_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String gateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.bank_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.bank_branch
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String bankBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.city
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.province
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.last_four_cardid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String lastFourCardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.expire_date
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Integer expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.status
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.is_default
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Byte isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.modify_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_bank_card.create_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.id
     *
     * @return the value of jk_user_bank_card.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.id
     *
     * @param id the value for jk_user_bank_card.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.uid
     *
     * @return the value of jk_user_bank_card.uid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.uid
     *
     * @param uid the value for jk_user_bank_card.uid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.media_id
     *
     * @return the value of jk_user_bank_card.media_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.media_id
     *
     * @param mediaId the value for jk_user_bank_card.media_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setMediaId(String mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.media_type
     *
     * @return the value of jk_user_bank_card.media_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.media_type
     *
     * @param mediaType the value for jk_user_bank_card.media_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.mer_cust_id
     *
     * @return the value of jk_user_bank_card.mer_cust_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getMerCustId() {
        return merCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.mer_cust_id
     *
     * @param merCustId the value for jk_user_bank_card.mer_cust_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setMerCustId(String merCustId) {
        this.merCustId = merCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.bank_card_type
     *
     * @return the value of jk_user_bank_card.bank_card_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getBankCardType() {
        return bankCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.bank_card_type
     *
     * @param bankCardType the value for jk_user_bank_card.bank_card_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setBankCardType(String bankCardType) {
        this.bankCardType = bankCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.card_id
     *
     * @return the value of jk_user_bank_card.card_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.card_id
     *
     * @param cardId the value for jk_user_bank_card.card_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.identity_type
     *
     * @return the value of jk_user_bank_card.identity_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getIdentityType() {
        return identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.identity_type
     *
     * @param identityType the value for jk_user_bank_card.identity_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setIdentityType(String identityType) {
        this.identityType = identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.identity_code
     *
     * @return the value of jk_user_bank_card.identity_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getIdentityCode() {
        return identityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.identity_code
     *
     * @param identityCode the value for jk_user_bank_card.identity_code
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setIdentityCode(String identityCode) {
        this.identityCode = identityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.card_holder
     *
     * @return the value of jk_user_bank_card.card_holder
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getCardHolder() {
        return cardHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.card_holder
     *
     * @param cardHolder the value for jk_user_bank_card.card_holder
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCardHolder(String cardHolder) {
        this.cardHolder = cardHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.bind_no
     *
     * @return the value of jk_user_bank_card.bind_no
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getBindNo() {
        return bindNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.bind_no
     *
     * @param bindNo the value for jk_user_bank_card.bind_no
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setBindNo(String bindNo) {
        this.bindNo = bindNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.usr_pay_agreement_id
     *
     * @return the value of jk_user_bank_card.usr_pay_agreement_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getUsrPayAgreementId() {
        return usrPayAgreementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.usr_pay_agreement_id
     *
     * @param usrPayAgreementId the value for jk_user_bank_card.usr_pay_agreement_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setUsrPayAgreementId(String usrPayAgreementId) {
        this.usrPayAgreementId = usrPayAgreementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.usr_busi_agreement_id
     *
     * @return the value of jk_user_bank_card.usr_busi_agreement_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getUsrBusiAgreementId() {
        return usrBusiAgreementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.usr_busi_agreement_id
     *
     * @param usrBusiAgreementId the value for jk_user_bank_card.usr_busi_agreement_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setUsrBusiAgreementId(String usrBusiAgreementId) {
        this.usrBusiAgreementId = usrBusiAgreementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.gate_id
     *
     * @return the value of jk_user_bank_card.gate_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getGateId() {
        return gateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.gate_id
     *
     * @param gateId the value for jk_user_bank_card.gate_id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setGateId(String gateId) {
        this.gateId = gateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.bank_name
     *
     * @return the value of jk_user_bank_card.bank_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.bank_name
     *
     * @param bankName the value for jk_user_bank_card.bank_name
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.bank_branch
     *
     * @return the value of jk_user_bank_card.bank_branch
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.bank_branch
     *
     * @param bankBranch the value for jk_user_bank_card.bank_branch
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.city
     *
     * @return the value of jk_user_bank_card.city
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.city
     *
     * @param city the value for jk_user_bank_card.city
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.province
     *
     * @return the value of jk_user_bank_card.province
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.province
     *
     * @param province the value for jk_user_bank_card.province
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.last_four_cardid
     *
     * @return the value of jk_user_bank_card.last_four_cardid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getLastFourCardid() {
        return lastFourCardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.last_four_cardid
     *
     * @param lastFourCardid the value for jk_user_bank_card.last_four_cardid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setLastFourCardid(String lastFourCardid) {
        this.lastFourCardid = lastFourCardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.expire_date
     *
     * @return the value of jk_user_bank_card.expire_date
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Integer getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.expire_date
     *
     * @param expireDate the value for jk_user_bank_card.expire_date
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setExpireDate(Integer expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.status
     *
     * @return the value of jk_user_bank_card.status
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.status
     *
     * @param status the value for jk_user_bank_card.status
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.is_default
     *
     * @return the value of jk_user_bank_card.is_default
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Byte getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.is_default
     *
     * @param isDefault the value for jk_user_bank_card.is_default
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setIsDefault(Byte isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.modify_time
     *
     * @return the value of jk_user_bank_card.modify_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.modify_time
     *
     * @param modifyTime the value for jk_user_bank_card.modify_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_bank_card.create_time
     *
     * @return the value of jk_user_bank_card.create_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_bank_card.create_time
     *
     * @param createTime the value for jk_user_bank_card.create_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_user_bank_card
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserBankCard other = (UserBankCard) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getMediaId() == null ? other.getMediaId() == null : this.getMediaId().equals(other.getMediaId()))
            && (this.getMediaType() == null ? other.getMediaType() == null : this.getMediaType().equals(other.getMediaType()))
            && (this.getMerCustId() == null ? other.getMerCustId() == null : this.getMerCustId().equals(other.getMerCustId()))
            && (this.getBankCardType() == null ? other.getBankCardType() == null : this.getBankCardType().equals(other.getBankCardType()))
            && (this.getCardId() == null ? other.getCardId() == null : this.getCardId().equals(other.getCardId()))
            && (this.getIdentityType() == null ? other.getIdentityType() == null : this.getIdentityType().equals(other.getIdentityType()))
            && (this.getIdentityCode() == null ? other.getIdentityCode() == null : this.getIdentityCode().equals(other.getIdentityCode()))
            && (this.getCardHolder() == null ? other.getCardHolder() == null : this.getCardHolder().equals(other.getCardHolder()))
            && (this.getBindNo() == null ? other.getBindNo() == null : this.getBindNo().equals(other.getBindNo()))
            && (this.getUsrPayAgreementId() == null ? other.getUsrPayAgreementId() == null : this.getUsrPayAgreementId().equals(other.getUsrPayAgreementId()))
            && (this.getUsrBusiAgreementId() == null ? other.getUsrBusiAgreementId() == null : this.getUsrBusiAgreementId().equals(other.getUsrBusiAgreementId()))
            && (this.getGateId() == null ? other.getGateId() == null : this.getGateId().equals(other.getGateId()))
            && (this.getBankName() == null ? other.getBankName() == null : this.getBankName().equals(other.getBankName()))
            && (this.getBankBranch() == null ? other.getBankBranch() == null : this.getBankBranch().equals(other.getBankBranch()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getLastFourCardid() == null ? other.getLastFourCardid() == null : this.getLastFourCardid().equals(other.getLastFourCardid()))
            && (this.getExpireDate() == null ? other.getExpireDate() == null : this.getExpireDate().equals(other.getExpireDate()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getIsDefault() == null ? other.getIsDefault() == null : this.getIsDefault().equals(other.getIsDefault()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_user_bank_card
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getMediaId() == null) ? 0 : getMediaId().hashCode());
        result = prime * result + ((getMediaType() == null) ? 0 : getMediaType().hashCode());
        result = prime * result + ((getMerCustId() == null) ? 0 : getMerCustId().hashCode());
        result = prime * result + ((getBankCardType() == null) ? 0 : getBankCardType().hashCode());
        result = prime * result + ((getCardId() == null) ? 0 : getCardId().hashCode());
        result = prime * result + ((getIdentityType() == null) ? 0 : getIdentityType().hashCode());
        result = prime * result + ((getIdentityCode() == null) ? 0 : getIdentityCode().hashCode());
        result = prime * result + ((getCardHolder() == null) ? 0 : getCardHolder().hashCode());
        result = prime * result + ((getBindNo() == null) ? 0 : getBindNo().hashCode());
        result = prime * result + ((getUsrPayAgreementId() == null) ? 0 : getUsrPayAgreementId().hashCode());
        result = prime * result + ((getUsrBusiAgreementId() == null) ? 0 : getUsrBusiAgreementId().hashCode());
        result = prime * result + ((getGateId() == null) ? 0 : getGateId().hashCode());
        result = prime * result + ((getBankName() == null) ? 0 : getBankName().hashCode());
        result = prime * result + ((getBankBranch() == null) ? 0 : getBankBranch().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getLastFourCardid() == null) ? 0 : getLastFourCardid().hashCode());
        result = prime * result + ((getExpireDate() == null) ? 0 : getExpireDate().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getIsDefault() == null) ? 0 : getIsDefault().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_user_bank_card
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", mediaId=").append(mediaId);
        sb.append(", mediaType=").append(mediaType);
        sb.append(", merCustId=").append(merCustId);
        sb.append(", bankCardType=").append(bankCardType);
        sb.append(", cardId=").append(cardId);
        sb.append(", identityType=").append(identityType);
        sb.append(", identityCode=").append(identityCode);
        sb.append(", cardHolder=").append(cardHolder);
        sb.append(", bindNo=").append(bindNo);
        sb.append(", usrPayAgreementId=").append(usrPayAgreementId);
        sb.append(", usrBusiAgreementId=").append(usrBusiAgreementId);
        sb.append(", gateId=").append(gateId);
        sb.append(", bankName=").append(bankName);
        sb.append(", bankBranch=").append(bankBranch);
        sb.append(", city=").append(city);
        sb.append(", province=").append(province);
        sb.append(", lastFourCardid=").append(lastFourCardid);
        sb.append(", expireDate=").append(expireDate);
        sb.append(", status=").append(status);
        sb.append(", isDefault=").append(isDefault);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}