package com.trj.jk.web.domain;

import java.util.Date;

public class UserActivity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_activity.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_activity.uid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_activity.activity_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Byte activityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_activity.log
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private String log;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_activity.activity_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Date activityTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_activity.modify_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_activity.create_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_activity.id
     *
     * @return the value of jk_user_activity.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_activity.id
     *
     * @param id the value for jk_user_activity.id
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_activity.uid
     *
     * @return the value of jk_user_activity.uid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_activity.uid
     *
     * @param uid the value for jk_user_activity.uid
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_activity.activity_type
     *
     * @return the value of jk_user_activity.activity_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Byte getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_activity.activity_type
     *
     * @param activityType the value for jk_user_activity.activity_type
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setActivityType(Byte activityType) {
        this.activityType = activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_activity.log
     *
     * @return the value of jk_user_activity.log
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_activity.log
     *
     * @param log the value for jk_user_activity.log
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setLog(String log) {
        this.log = log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_activity.activity_time
     *
     * @return the value of jk_user_activity.activity_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Date getActivityTime() {
        return activityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_activity.activity_time
     *
     * @param activityTime the value for jk_user_activity.activity_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setActivityTime(Date activityTime) {
        this.activityTime = activityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_activity.modify_time
     *
     * @return the value of jk_user_activity.modify_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_activity.modify_time
     *
     * @param modifyTime the value for jk_user_activity.modify_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_activity.create_time
     *
     * @return the value of jk_user_activity.create_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_activity.create_time
     *
     * @param createTime the value for jk_user_activity.create_time
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_user_activity
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserActivity other = (UserActivity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getActivityType() == null ? other.getActivityType() == null : this.getActivityType().equals(other.getActivityType()))
            && (this.getLog() == null ? other.getLog() == null : this.getLog().equals(other.getLog()))
            && (this.getActivityTime() == null ? other.getActivityTime() == null : this.getActivityTime().equals(other.getActivityTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_user_activity
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getActivityType() == null) ? 0 : getActivityType().hashCode());
        result = prime * result + ((getLog() == null) ? 0 : getLog().hashCode());
        result = prime * result + ((getActivityTime() == null) ? 0 : getActivityTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_user_activity
     *
     * @mbg.generated Tue Jun 13 16:01:17 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", activityType=").append(activityType);
        sb.append(", log=").append(log);
        sb.append(", activityTime=").append(activityTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}