package com.trj.jk.web.domain;

import java.util.Date;

public class UserFaceLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_face_log.id
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_face_log.uid
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_face_log.type
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_face_log.status
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_face_log.remark
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_face_log.create_person
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_face_log.update_person
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    private String updatePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_face_log.modify_time
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_face_log.create_time
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk_user_face_log.result
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_face_log.id
     *
     * @return the value of jk_user_face_log.id
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_face_log.id
     *
     * @param id the value for jk_user_face_log.id
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_face_log.uid
     *
     * @return the value of jk_user_face_log.uid
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_face_log.uid
     *
     * @param uid the value for jk_user_face_log.uid
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_face_log.type
     *
     * @return the value of jk_user_face_log.type
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_face_log.type
     *
     * @param type the value for jk_user_face_log.type
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_face_log.status
     *
     * @return the value of jk_user_face_log.status
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_face_log.status
     *
     * @param status the value for jk_user_face_log.status
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_face_log.remark
     *
     * @return the value of jk_user_face_log.remark
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_face_log.remark
     *
     * @param remark the value for jk_user_face_log.remark
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_face_log.create_person
     *
     * @return the value of jk_user_face_log.create_person
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_face_log.create_person
     *
     * @param createPerson the value for jk_user_face_log.create_person
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_face_log.update_person
     *
     * @return the value of jk_user_face_log.update_person
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_face_log.update_person
     *
     * @param updatePerson the value for jk_user_face_log.update_person
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_face_log.modify_time
     *
     * @return the value of jk_user_face_log.modify_time
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_face_log.modify_time
     *
     * @param modifyTime the value for jk_user_face_log.modify_time
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_face_log.create_time
     *
     * @return the value of jk_user_face_log.create_time
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_face_log.create_time
     *
     * @param createTime the value for jk_user_face_log.create_time
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk_user_face_log.result
     *
     * @return the value of jk_user_face_log.result
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk_user_face_log.result
     *
     * @param result the value for jk_user_face_log.result
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_user_face_log
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserFaceLog other = (UserFaceLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getUpdatePerson() == null ? other.getUpdatePerson() == null : this.getUpdatePerson().equals(other.getUpdatePerson()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_user_face_log
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getUpdatePerson() == null) ? 0 : getUpdatePerson().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jk_user_face_log
     *
     * @mbg.generated Thu Jul 13 10:46:53 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", updatePerson=").append(updatePerson);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", result=").append(result);
        sb.append("]");
        return sb.toString();
    }
}